const COUNTRIES_2 = [
{ iso:"LT", name:"Lithuania", flag:"🇱🇹", region:"North", eu:true, maturity:4, lastUpdate:"2026-07-03",
  transposed:true, onTime:true, delayMonths:0, lawInForce:"2024-10-18", fw:"final",
  law:"Cybersecurity Law No. XII-1428 + government resolution of 12 Nov 2024",
  fwName:"Description of cybersecurity requirements - 12 themes (ISO 27001-based)",
  reqEE:119, reqIE:107, complianceEE:12, complianceIE:12,
  auditBody:"National authority (NKSC)", auditFreqEE:36, auditFreqIE:36, selfAssessFreq:null,
  regTool:"Authority-driven (NKSC registry via KSIS)", incidentMethod:"Web platform (national plan)",
  summary:"Transposed on time; NKSC registered entities by Apr 2025; 12-theme ISO-based framework; audits every 3 years.",
  authorities:[ { name:"NKSC", role:"National Cyber Security Centre - supervision, registry, technical assistance" } ],
  sections:{
    fw:["12 main themes combining specific requirements (policies, training, business continuity) and technical requirements (network security, encryption); grounded in ISO/IEC 27001.","Organisational requirements within 12 months of registry entry, technical measures within 24 months.","Local specificities: availability thresholds >96%/99% for critical IS; mandatory ISP contracts with response times and DoS protection (incl. 24/7)."],
    reg:["NKSC selected and registered entities in the KSIS registry by 17 Apr 2025 (authority-driven); entities could contest their categorisation.","Self-check questionnaire available from the Ministry of Defence; after confirmation, entities connect to KSIS and provide activity data."],
    inc:["Notifications to the NKSC per the National Cyber Incident Management Plan via the dedicated platform; quantified thresholds (operational, financial, third-party damage, physical security)."],
    aud:["Independent cybersecurity audit at least every 3 years; targeted audits at entity's cost when high risk detected; audits max 4 months (+2 extension).","Sectoral and NKSC-led audits start officially in 2027; first ex-post EE compliance assessments due 1 Jan 2029."],
    scope:["Universities and research institutions added; scientific research for commercial purposes explicitly included.","Public administration (central, regional, municipal) classified EE - subject to corrective orders and public naming instead of fines."],
    other:["Explicit links to DORA, eIDAS, GDPR."],
    reco:["Managers: cybersecurity training every 2 years, documented; vulnerability disclosure embargo 90 days; NKSC can deploy sensors on EE networks."] },
  timeline:[
    { date:"2024-10-18", text:"Cybersecurity Law No. XII-1428 in force - on time" },
    { date:"2024-11-12", text:"Government resolution amending the 2018 implementation text in force" },
    { date:"2025-04-17", text:"NKSC completes initial registry of cybersecurity entities (KSIS)" } ],
  next:["2027: sectoral and NKSC audits begin; 1 Jan 2029: first ex-post EE compliance assessments."],
  sources:[
    { name:"NKSC", url:"https://www.nksc.lt", type:"official" },
    { name:"e-Seimas (legislation)", url:"https://e-seimas.lrs.lt", type:"official" } ] },

{ iso:"MT", name:"Malta", flag:"🇲🇹", region:"South", eu:true, maturity:4, lastUpdate:"2026-07-03",
  transposed:true, onTime:false, delayMonths:5, lawInForce:"2025-04-08", fw:"final",
  law:"Legal Notice 71 of 2025 (+ Legal Notice 22 of 2026 - full entry into force)",
  fwName:"Belgian CyFun adopted as national framework (Dec 2025)",
  reqEE:218, reqIE:133, complianceEE:18, complianceIE:18,
  auditBody:"Multiple (CIPD + sector regulators)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"CIPD national registry (reviewed every 2 years)", incidentMethod:"Report to CSIRTMalta",
  summary:"Law Apr 2025; joined the CyFun Scheme Owner Group and adopted the Belgian framework; fully applicable since 23 Jan 2026.",
  authorities:[
    { name:"MHSE", role:"Ministry for Home Affairs, Security and Employment" },
    { name:"CIPD", role:"Critical Infrastructure Protection Department - national supervisory authority" },
    { name:"CSIRTMalta", role:"National CSIRT - incident notifications, coordinated vulnerability disclosure" } ],
  sections:{
    fw:["Malta officially adopted the Belgian CyFun framework (ISO 27001, IEC 62443, NIST CSF, CIS Controls based) after joining the CyberFundamentals Scheme Owner Group on 12 Dec 2025."],
    reg:["National self-registration mechanism maintained by the CIPD; registry reviewed at least every 2 years; changes notified within 3 months."],
    inc:["Incident notifications submitted to CSIRTMalta; National Coordinated Vulnerability Disclosure Policy (NCVDP) in place, CSIRTMalta acting as trusted intermediary."],
    aud:["CIPD powers: on-site inspections, audits, security scans, information requests, data access; sector regulators (MCA for ICT, MFSA for finance) also supervise.","Entities must appoint a qualified auditor approved by the authority (valid international/EU certification or background check)."],
    scope:["Public administration incl. central government and, after risk assessment, regional entities; national security/defence/law-enforcement excluded.","Criminal Code (Computer Misuse) being revised to align vulnerability-reporting frameworks."] },
  timeline:[
    { date:"2025-04-08", text:"Legal Notice 71 of 2025 transposes NIS 2" },
    { date:"2025-12-12", text:"Malta joins the CyberFundamentals Scheme Owner Group - Belgian CyFun adopted" },
    { date:"2026-01-23", text:"Full entry into force of all provisions (Legal Notice 22 of 2026)" } ],
  next:["Practical implementation depends on upcoming CIPD decisions on registration modalities and requirements."],
  sources:[
    { name:"CIPD (MHSE)", url:"", type:"official" },
    { name:"Malta Government Gazette / legislation.mt", url:"https://legislation.mt", type:"official" } ] },

{ iso:"PT", name:"Portugal", flag:"🇵🇹", region:"South", eu:true, maturity:4, lastUpdate:"2026-06-25",
  transposed:true, onTime:false, delayMonths:13, lawInForce:"2026-04-03", fw:"final",
  law:"Regime Jurídico da Cibersegurança - Decreto-Lei 125/2025 + Regulamento 756/2026",
  fwName:"QNRCS v2 - 6 objectives, 117 measures, 3 levels (Básico/Substancial/Elevado)",
  reqEE:117, reqIE:117, complianceEE:26, complianceIE:26,
  auditBody:"Authority or qualified independent entity", auditFreqEE:12, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Platform (MyCiber)", incidentMethod:"Web platform (MyCiber forms)",
  summary:"RJC in force Apr 2026 (~18-month delay); QNRCS v2 framework final since 22 June 2026; compliance deadline 22 June 2028.",
  authorities:[
    { name:"CNCS", role:"Centro Nacional de Cibersegurança - national authority (sector authorities may supplement)" } ],
  sections:{
    fw:["QNRCS v2 adopted as national framework: 6 objectives (Govern, Identify, Protect, Detect, Respond, Recover), 117 measures; levels Básico/Substancial/Elevado for private entities, groups A/B for public.","Based on NIST CSF 2.0, ISO 27001 and CIS CSC v8.1; voluntary certification via EC QNRCS, ISO/IEC 27001 or DNP TS 4577-1 (Selo Digital) gives presumption of conformity.","Compliance deadline: 22 June 2028."],
    reg:["Registration on MyCiber within 60 days of go-live (before 22 Aug 2026) or within 30 days of gaining EE/IE status; provisional then definitive registry with 10-working-day hearing.","Data: name, tax ID, sector, entity type, addresses, EU member states served, headcount, turnover; cybersecurity officer + permanent 24/7 contact point designated via the platform."],
    inc:["Notifications via MyCiber forms in three stages (initial, end-of-significant-impact, final/interim); email or phone fallback; NIS 2 deadlines.","Significant-incident definition per Implementing Regulation (EU) 2024/2690 where applicable; CNCS technical instruction pending for the rest."],
    aud:["EE: ex-ante supervision (on-site/remote inspections, regular or targeted audits, random checks); IE: ex-post on evidence of non-compliance; targeted audit costs borne by the entity."],
    scope:["'Relevant public entities' - Portuguese specificity: Group A (≥250 staff, obligations close to IE) and Group B (75-249 staff, lighter obligations)."],
    other:["Law 46/2018 and Decree-Law 65/2021 repealed; DORA entities notify ICT incidents to DORA authorities but keep RJC officer/contact-point duties."] },
  timeline:[
    { date:"2025-12-04", text:"Decreto-Lei 125/2025 published - transposes NIS 2" },
    { date:"2026-04-03", text:"RJC enters into force (~18 months after the EU deadline)" },
    { date:"2026-06-22", text:"Regulamento 756/2026 published; QNRCS v2 becomes the national framework - regime fully operational" } ],
  next:["Registration on MyCiber before 22 Aug 2026; two CNCS technical instructions pending (significant-incident definition, certification equivalence matrix); compliance by 22 Jun 2028."],
  sources:[
    { name:"CNCS", url:"https://www.cncs.gov.pt", type:"official" },
    { name:"MyCiber", url:"https://myciber.gov.pt", type:"official" },
    { name:"Diário da República", url:"https://diariodarepublica.pt", type:"official" } ] },

{ iso:"SK", name:"Slovakia", flag:"🇸🇰", region:"East", eu:true, maturity:4, lastUpdate:"2026-07-06",
  transposed:true, onTime:false, delayMonths:2, lawInForce:"2025-01-01", fw:"final",
  law:"Act 366/2024 amending Act 69/2018 + decrees 226/2025 & 227/2025",
  fwName:"19-theme national framework (decree 227/2025), incl. OT measures",
  reqEE:151, reqIE:142, complianceEE:12, complianceIE:12,
  auditBody:"National authority (NBÚ)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Platform (JISKB)", incidentMethod:"Web platform (JISKB)",
  summary:"In force Jan 2025; JISKB platform for registration and incidents; 19-theme framework with explicit 3-2-1 backup rule.",
  authorities:[
    { name:"NBÚ", role:"National Security Authority - supervision (with sector ministries)" },
    { name:"SK-CERT", role:"National Cybersecurity Centre - 24/7 incident management, coordinated disclosure" } ],
  sections:{
    fw:["Decree 227/2025 sets minimum measures across 19 themes: governance, risk, supply chain, IAM, cryptography (annual robustness reassessment), OT safeguards, business continuity.","Local specificities: explicit 3-2-1 backup rule; incident definition includes averted threats and identified vulnerabilities.","Scope of measures determined by risk analysis (annex 1 of decree 226/2025); security documentation kept current for NBÚ inspection."],
    reg:["Registration via JISKB within 60 days of starting activity; law applicable 30 days after registry entry; NBÚ online classification wizard available.","Entities without EU seat must appoint a representative in Slovakia (cloud, DNS); changes notified within 14 days."],
    inc:["Significant incidents reported via JISKB since 1 Jan 2025; criteria in annex I of decree 226/2025; annexes II-III define report content."],
    aud:["EE: mandatory certified audits, first within 2 years of registration; IE: self-assessment via JISKB, certified audit within 5 years.","NIS 1 entities: 2024 audit deadline extended to 30 Sep 2025, previous audit obligations usable until Dec 2026; full compliance for already-registered entities by 31 Dec 2026."],
    scope:["Thermal energy sub-sector added; water & atmosphere sector (drinking/waste water, meteorology, hydraulic structures); nuclear energy follows the law in addition to Atomic Act 541/2004.","Public administration: 3 ministries as competent authorities; large municipalities and regions included if disruption impacts public order/health; public entities face corrective orders, not fines."],
    other:["NBÚ can temporarily suspend executives on repeated failures (private sector); state of cyber crisis can be declared."] },
  timeline:[
    { date:"2025-01-01", text:"Amendment to Act 69/2018 (Act 366/2024) in force" },
    { date:"2025-09-01", text:"Decrees 226/2025 (incidents) and 227/2025 (minimum requirements) in force" },
    { date:"2025-09-30", text:"Extended audit deadline for former NIS 1 entities" } ],
  next:["Full compliance of registered entities by 31 Dec 2026."],
  sources:[
    { name:"NBÚ", url:"https://www.nbu.gov.sk", type:"official" },
    { name:"SK-CERT", url:"https://www.sk-cert.sk", type:"official" },
    { name:"Slov-Lex (legislation)", url:"https://www.slov-lex.sk", type:"official" } ] },

{ iso:"SI", name:"Slovenia", flag:"🇸🇮", region:"East", eu:true, maturity:4, lastUpdate:"2026-07-06",
  transposed:true, onTime:false, delayMonths:8, lawInForce:"2025-06-19", fw:"final",
  law:"Information Security Act ZInfV-1 (adopted 23 May 2025, emergency procedure)",
  fwName:"Law-defined measures (art. 21-22) referencing EU/international standards - no dedicated framework planned",
  reqEE:null, reqIE:null, complianceEE:18, complianceIE:18,
  auditBody:"Multiple (URSIV + AKOS)", auditFreqEE:24, auditFreqIE:24, selfAssessFreq:24,
  regTool:"Form (URSIV online form / email fallback)", incidentMethod:"Email to SI-CERT (platform within 1 year)",
  summary:"ZInfV-1 in force June 2025; self-registration closed Dec 2025; risk measures due Dec 2026 (Jun 2026 for ex-NIS1).",
  authorities:[
    { name:"URSIV", role:"Government Office for Information Security - supervision" },
    { name:"AKOS", role:"Supervisor for electronic communications, media, digital services" },
    { name:"SI-CERT", role:"National CSIRT" } ],
  sections:{
    fw:["Security documentation (art. 21) and risk-management measures (art. 22) reference European and international standards; decrees pending to map obligations to ISO/IEC 27001.","Deadlines: 18 months after entry into force (19 Dec 2026); 12 months for entities already essential under the previous law (19 Jun 2026)."],
    reg:["Self-registration within 6 months (by 19 Dec 2025) via the URSIV online form; data includes MŠ ID, NACE code, security officer, public IP blocks, ASN, domain names."],
    inc:["Until the dedicated platform ships (within 1 year), notifications by email to SI-CERT; voluntary reporting of cyber threats and near-misses possible."],
    aud:["Random inspections for EE; IE inspected on evidence of breach; on-site, remote and security audits.","EE compliance assessment every 2 years; IE self-assessment every 2 years."],
    scope:["Research institutions added (excluding education); general threshold ≥50 staff AND ≥€10M turnover/balance sheet except listed exceptions.","Public administration incl. national security/defence/law-enforcement entities (annex III) and urban municipalities; public entities face corrective orders, not fines."],
    other:["DORA for finance; EU cybersecurity certification framework (Regulation 2019/881) integrated.","Logs kept ≥6 months (critical entities: on Slovenian territory); board approval of cyber programmes + training every 4 years; background checks allowed for sensitive positions."] },
  timeline:[
    { date:"2025-05-23", text:"ZInfV-1 adopted by the National Assembly (emergency procedure after EC formal notice)" },
    { date:"2025-06-19", text:"Law enters into force" },
    { date:"2025-12-19", text:"Self-registration deadline (6 months)" } ],
  next:["Government decrees mapping risk-management obligations to ISO/IEC 27001 expected; risk measures due 19 Jun / 19 Dec 2026."],
  sources:[
    { name:"URSIV (gov.si)", url:"https://www.gov.si", type:"official" },
    { name:"SI-CERT", url:"https://www.cert.si", type:"official" },
    { name:"Uradni list (Official Gazette)", url:"https://www.uradni-list.si", type:"official" } ] },

{ iso:"EE", name:"Estonia", flag:"🇪🇪", region:"North", eu:true, maturity:4, lastUpdate:"2026-07-02",
  transposed:true, onTime:false, delayMonths:14, lawInForce:"2026-01-01", fw:"final",
  law:"Cybersecurity Act amendment (Bill 739-SE), in force 1 Jan 2026",
  fwName:"E-ITS - ~1,600 measures in modules (BSI IT-Grundschutz + EVS-ISO/IEC 27001 based), updated every autumn",
  reqEE:100, reqIE:100, complianceEE:36, complianceIE:36,
  auditBody:"National authority (RIA) + annual entity audits", auditFreqEE:12, auditFreqIE:12, selfAssessFreq:null,
  regTool:"Platform (state portal eesti.ee)", incidentMethod:"Web platform ('Raport', CERT-EE) or email",
  summary:"Law in force Jan 2026; registration due 1 Apr 2026 on eesti.ee; E-ITS framework; full compliance by Jan 2029.",
  authorities:[
    { name:"RIA", role:"Information System Authority - single point of contact, registry, incidents & crises" },
    { name:"NCSC-EE", role:"National Cybersecurity Centre - controls and audits" } ],
  sections:{
    fw:["Estonia meets NIS 2 minimums and details them via E-ITS: ~1,600 baseline measures grouped in modules (ISMS, OPS, INF, APP, SYS, DER…), each tagged basic/standard/high; entities apply the measures relevant to their assets.","E-ITS validation requires a dedicated audit - no automatic EE/IE split inside the framework; compliance with E-ITS also counts for referenced frameworks (e.g. German BSI certification).","Full compliance within 3 years (by 1 Jan 2029); §31 entities within 3 months; vital-service providers get 5 years from designation."],
    reg:["Registration within 3 months of the law (by 1 Apr 2026) or of gaining EE/IE status, via eesti.ee with the RIA; changes within 2 weeks (3 months for digital services); non-EU digital providers appoint a representative.","Note: RIA withdrew its automated scope self-assessment tool early 2026, judged too complex to be reliable."],
    inc:["First notification within 24h (except national-security entities), report within 72h, final report within 1 month; 'Raport' platform run by CERT-EE, simple email accepted."],
    aud:["Annual security audits to verify effectiveness; no more than 12 months between two audits; targeted EE audits at entity cost (exceptions by decree); mutual evaluation possible, regular internal audit counts as independent review."],
    scope:["Size thresholds clarified (≥50 staff + ≥€10M CA for IE; ≥250 staff + ≥€43M balance/€50M CA for some EE); R&D centres added; IS suppliers (IXP, MSP, MSSP, ITS) automatically EE regardless of size.","Public sector additions: public policy analysis centres, RMK (state forest), local authority associations."],
    other:["Board member(s) formally responsible for approving security measures, with regular training; absent designation, the whole board is liable; info-sharing between entities regulated (RIA informed)."] },
  timeline:[
    { date:"2025-12-10", text:"Bill 739-SE adopted by the Riigikogu" },
    { date:"2025-12-30", text:"Law published in Riigi Teataja; in force 1 Jan 2026" },
    { date:"2026-04-01", text:"Registration deadline on eesti.ee (3 months after entry into force)" } ],
  next:["During 2026: guidelines completing E-ITS; full compliance by 1 Jan 2029."],
  sources:[
    { name:"RIA", url:"https://www.ria.ee", type:"official" },
    { name:"Riigi Teataja (Official Gazette)", url:"https://www.riigiteataja.ee", type:"official" } ] },

{ iso:"RO", name:"Romania", flag:"🇷🇴", region:"East", eu:true, maturity:3, lastUpdate:"2026-07-06",
  transposed:true, onTime:false, delayMonths:8, lawInForce:"2024-12-31", fw:"temporary",
  law:"Emergency Ordinance OUG 155/2024 + Law 124/2025 + DNSC orders 1/2025 & 2/2025",
  fwName:"DNSC orders on cybersecurity measures; Belgian CyFun officially recognised - further orders pending",
  reqEE:218, reqIE:133, complianceEE:18, complianceIE:18,
  auditBody:"National authority (DNSC)", auditFreqEE:24, auditFreqIE:24, selfAssessFreq:12,
  regTool:"Offline form → NIS2@RO platform (pending)", incidentMethod:"Web platform (PNRISC)",
  summary:"OUG in force Dec 2024; DNSC orders Aug 2025; recognises Belgian CyFun; annual maturity self-assessment; external audit 1 year after registration.",
  authorities:[ { name:"DNSC", role:"National Cyber Security Directorate - regulator, CVD coordinator" } ],
  sections:{
    fw:["DNSC director issued two orders on cybersecurity measures; Romania joined the CyberFundamentals Scheme Owner Group (Oct 2024) and officially recognises Belgian CyFun.","Annual self-assessment of risk-management maturity submitted to the DNSC; EE remediation plan within 30 days of self-assessment, endorsed by management.","INFORB project (with Bulgarian MEG): practical guides for the food sector."],
    reg:["Registration within 30 days of qualifying - effectively enforceable from 20 Aug 2025 (DNSC orders), so ~19/20 Sep 2025; DNSC identification decision within 60 days (EE) / 150 days (IE).","Interim offline tool (form emailed to the DNSC) until the NIS2@RO platform launches."],
    inc:["Significant or cross-border incidents notified to the DNSC via the PNRISC platform; 24h warning, 72h initial notification, final report within 1 month."],
    aud:["External compliance audit mandatory 1 year after registration, then every 2 years; results to the DNSC within 5 days; ad-hoc audits after major incidents or significant changes."],
    scope:["CDN services, data-centre services and MSSPs explicitly included."],
    other:["DNSC public 'Blacklist' platform of malicious domains; Romanian translation of the Belgian selection tool published Dec 2025."] },
  timeline:[
    { date:"2024-12-31", text:"OUG 155/2024 adopted and in force - founding text" },
    { date:"2025-07-10", text:"Law 124/2025 approves and strengthens the OUG" },
    { date:"2025-08-20", text:"DNSC orders 1/2025 (registration) and 2/2025 (risk methodology) in force" },
    { date:"2025-12-12", text:"Belgian selection tool published in Romanian" },
    { date:"2026-01-05", text:"Public consultation on risk management and board responsibilities" } ],
  next:["Additional regulations on risk-management measures and incident-reporting standards expected; sector authorities may specify details."],
  sources:[
    { name:"DNSC", url:"https://www.dnsc.ro", type:"official" },
    { name:"Monitorul Oficial", url:"", type:"official" } ] },

{ iso:"AT", name:"Austria", flag:"🇦🇹", region:"East", eu:true, maturity:3, lastUpdate:"2026-06-22",
  transposed:true, onTime:false, delayMonths:14, lawInForce:"2026-10-01", fw:"none",
  law:"NISG 2026 (BGBl. 94/2025, published 23 Dec 2025) - in force 1 Oct 2026",
  fwName:"Implementing regulations per sector to be issued by the Cybersicherheitsbehörde",
  reqEE:null, reqIE:null, complianceEE:6, complianceIE:6,
  auditBody:"External accredited auditors", auditFreqEE:24, auditFreqIE:24, selfAssessFreq:36,
  regTool:"Secure electronic channel (platform TBA)", incidentMethod:"Web platforms (3, by entity type/sector)",
  summary:"NISG 2026 adopted Dec 2025, applies from Oct 2026 (9-month transition); new federal cybersecurity authority; self-declaration by Jan 2028.",
  authorities:[
    { name:"Bundesamt für Cybersicherheit", role:"New federal cybersecurity authority (under BMI, organisationally independent) - competent authority, SPOC, national coordination" },
    { name:"GovCERT", role:"Public-administration CSIRT, interim national CSIRT" },
    { name:"Austrian HealthCERT", role:"Health-sector CSIRT" } ],
  sections:{
    fw:["Risk-management measures cover the 10 NIS 2 areas (risk analysis, incidents, continuity, supply chain, development, hygiene/training, cryptography, access control, MFA); sector implementing regulations pending.","EU sector rules (incl. DORA) take precedence where equivalent; CER definitions integrated; other recognised certifications may be considered."],
    reg:["Registration within 3 months of entry into force (by 1 Jan 2027) via a secure electronic channel; changes within 2 weeks (3 months for seat address / EE-IE status)."],
    inc:["Online notification via 3 platforms (public administration, essential/digital services, energy); NIS 2 deadlines, except trust services: full report within 24h."],
    aud:["Proactive supervision for EE (on-site/remote inspections, scans, ad-hoc audits); reactive for IE; mandatory self-declaration within 12 months of the registration obligation (by 1 Jan 2028).","On request: audit by accredited independent auditor (EE: 2 months to prove compliance; IE: 2 years); audit plan notified 1 month ahead; auditors accredited on qualifications (≥3 years, ≥20h/week) and exam.","From 1 Oct 2028 authorities may request proof of compliance via an independent auditor."],
    scope:["ICT/DNS grouped as 'digital infrastructure' with requirements beyond NIS 2; health under GTelG 2012; research treated as an activity, not a sector.","Federal administration = EE regardless of size; Länder administration = IE; municipalities, education, courts, Parliament, national bank excluded."],
    other:["Fines: EE up to €10M/2%, IE €7M/1.4%; registration/cooperation failures up to €50k (€100k repeat); temporary management bans with companies-register entry."] },
  timeline:[
    { date:"2024-07-03", text:"First bill (NISG 2024) rejected by the National Council" },
    { date:"2025-11-20", text:"NISG 2026 bill presented by the government" },
    { date:"2025-12-18", text:"NISG 2026 adopted (Nationalrat, then Bundesrat)" },
    { date:"2025-12-23", text:"Published in the Federal Gazette (BGBl. 94/2025)" },
    { date:"2026-01-30", text:"Official webinar on NISG 2026 and NIS 2" } ],
  next:["1 Oct 2026: entry into force; 1 Jan 2027: registration deadline; 1 Jan 2028: self-declarations; 1 Oct 2028: auditor-backed proof requests possible."],
  sources:[
    { name:"RIS / Federal Gazette", url:"https://www.ris.bka.gv.at", type:"official" },
    { name:"Federal Chancellery scope guide", url:"", type:"official" } ] }
];
