const COUNTRIES_1 = [
{ iso:"BE", name:"Belgium", flag:"🇧🇪", region:"West", eu:true, maturity:4, lastUpdate:"2026-06-18",
  transposed:true, onTime:true, delayMonths:0, lawInForce:"2024-10-18", fw:"final",
  law:"NIS 2 Act of 26 April 2024 + Royal Decree of 9 June 2024",
  fwName:"CyFun 2025 (CyberFundamentals, NIST CSF 2.0-based)",
  reqEE:218, reqIE:133, complianceEE:18, complianceIE:18,
  auditBody:"External accredited body", auditFreqEE:12, auditFreqIE:12, selfAssessFreq:12,
  regTool:"Platform + guide (atwork.safeonweb.be)", incidentMethod:"Web platform (CCB)",
  summary:"Transposed on time; CyFun 2025 framework; first ex-ante EE checks under way since April 2026.",
  authorities:[
    { name:"CCB", role:"Centre for Cybersecurity Belgium - national authority, CyFun certification, incident handling" },
    { name:"NCCN", role:"National Crisis Centre - national cyber crisis management plan (with CCB)" } ],
  sections:{
    fw:["CyFun framework with three assurance levels (Small ≈25, Basic ≈50, Important ≈75 measures), complemented by NIST CSF, ISO 27001/27002, IEC 62443 and CIS Controls references.","CyFun 2025 (published 1 Oct 2025, NIST CSF 2.0 + governance category) will be the only accepted version after the transition period.","Presumption of conformity via the CyFun Conformity Assessment Scheme (CAS) or ISO/IEC 27001 (SoA submitted by 18 Apr 2026, certificate by 18 Apr 2027)."],
    reg:["Registration on atwork.safeonweb.be was due by 18 Mar 2025 (5 months after entry into force).","Any change to company information must be notified within 2 weeks."],
    inc:["Significant incidents reported to the CCB within 24h, full report within 1 month, via the dedicated platform (guide published by the CCB).","Notification must include detailed description, severity/impact, root cause, mitigation measures and cross-border impact."],
    aud:["EE: mandatory regular conformity assessment; first control 18 Apr 2026 (18 months after entry into force), then annual checks for EE and IE.","Ex-ante inspections possible for EE at any time; federal public sector assessed by the Federal Internal Audit Service."],
    scope:["Sector list can be extended by royal decree; CER-designated critical entities are automatically EE.","Local authorities not systematically included (case-by-case designation as 'strategic entity' by the CCB); public administration entities exempt from administrative fines."],
    other:["Financial entities under DORA are exempt from the security rules but must still register with the CCB and notify significant incidents."],
    reco:["Register with the CCB, choose CyFun vs ISO 27001 (Wavestone recommends CyFun unless ISO 27001 already in place), run gap analysis and remediation plan before the April 2026/2027 milestones."] },
  timeline:[
    { date:"2024-04-26", text:"NIS 2 Act voted in plenary (published 17 May 2024)" },
    { date:"2024-10-18", text:"Law enters into force - on time" },
    { date:"2025-10-01", text:"CyFun 2025 published (NIST CSF 2.0 base, governance category added)" },
    { date:"2025-12-19", text:"CER law adopted; designated critical entities become NIS 2 EE automatically" },
    { date:"2026-04-18", text:"Compliance deadline passed; CCB inspection service starts ex-ante verification of EE" } ],
  next:["By 18 Apr 2027: end of CyFun transition period; general compliance progress report due."],
  sources:[
    { name:"CCB - ccb.belgium.be", url:"https://ccb.belgium.be", type:"official" },
    { name:"Safeonweb for organisations", url:"https://atwork.safeonweb.be", type:"official" },
    { name:"Belgian Official Gazette (Moniteur belge)", url:"", type:"official" } ] },

{ iso:"HR", name:"Croatia", flag:"🇭🇷", region:"South", eu:true, maturity:4, lastUpdate:"2026-07-02",
  transposed:true, onTime:true, delayMonths:0, lawInForce:"2024-02-15", fw:"final",
  law:"Cybersecurity Act NN 14/2024 + Cybersecurity Regulation NN 135/2024",
  fwName:"National framework - 13 themes, 145 controls (ISO 27001/2 & NIST 800-53 aligned)",
  reqEE:28, reqIE:21, complianceEE:12, complianceIE:12,
  auditBody:"External accredited body", auditFreqEE:24, auditFreqIE:24, selfAssessFreq:24,
  regTool:"Authority-driven categorisation (no self-registration)", incidentMethod:"Web platform (PiXi / CARNET)",
  summary:"Transposed on time; authority-driven categorisation; 145-control framework with 3 criticality levels.",
  authorities:[
    { name:"NCSC-HR", role:"National Cybersecurity Centre (within SOA) - central authority" },
    { name:"ZSIS", role:"Information Systems Security Bureau - certification schemes, auditor accreditation" },
    { name:"CARNET / ZSIS CSIRTs", role:"Sectoral CSIRTs (banking, digital infrastructure / energy, transport, health, public admin)" } ],
  sections:{
    fw:["13 main themes, catalogue of 145 controls aligned with ISO 27001/2 and NIST 800-53; measures apply per criticality level (basic / medium / advanced) assigned by national risk assessment.","Sub-measures tagged A (mandatory), B (conditional), C (recommended); all measures cover both IT and OT.","Compliance required within 1 year of receiving the categorisation notification."],
    reg:["Entities do not self-register: competent authorities identify and notify each entity (spring 2025 wave).","Requested data must be transmitted within 15 days of categorisation; lists verified every 2 years."],
    inc:["Significant incidents notified to the competent CERT via forms on the PiXi platform (CARNET).","Beneficiaries must be informed within 72h; note: the Croatian law does not replicate the 24h early-warning explicitly."],
    aud:["EE: cybersecurity audit at least every 2 years by accredited auditors (ISO 27001, CyFun, KRITIS certifications recognised); conclusions to authorities within 8 days, costs borne by entities.","IE: self-assessment at least every 2 years; audit only on authority request."],
    scope:["Any entity supplying a service/good of major societal or economic importance can be designated regardless of size; e-invoicing exchange platforms are EE; public communication network providers are IE.","Education entities can be IE regardless of size; special physical-security measures for digital infrastructure entities."],
    other:["DORA provisions integrated (third-party ICT provider definitions); CER directive not referenced."] },
  timeline:[
    { date:"2024-02-15", text:"Cybersecurity Act (NN 14/2024) enters into force - on time" },
    { date:"2024-11-30", text:"Cybersecurity Regulation (NN 135/2024) in force: classification criteria, risk measures, incident notification" },
    { date:"2025-03-14", text:"NCSC-HR: initial categorisation under way; entities notified by mid-April 2025" },
    { date:"2025-06-30", text:"ZSIS publishes self-assessment guidelines (control calculator, risk framework, 145-control catalogue)" },
    { date:"2025-08-15", text:"Public consultation on certification rules for cybersecurity audits closed" } ],
  next:["During 2026: additional implementing regulations and new National Cyber Security Strategy expected."],
  sources:[
    { name:"NCSC-HR (SOA)", url:"", type:"official" },
    { name:"ZSIS", url:"", type:"official" },
    { name:"Narodne novine (Official Gazette)", url:"https://narodne-novine.nn.hr", type:"official" } ] },

{ iso:"CZ", name:"Czechia", flag:"🇨🇿", region:"East", eu:true, maturity:4, lastUpdate:"2026-07-06",
  transposed:true, onTime:false, delayMonths:12, lawInForce:"2025-11-01", fw:"final",
  law:"Cybersecurity Act No. 264/2025 Coll. + implementing decrees of 14 Oct 2025",
  fwName:"Tiered regime - higher obligations: 14 org. themes (169 measures) + 11 technical (127); lower: 13 themes (81 measures)",
  reqEE:296, reqIE:81, complianceEE:12, complianceIE:12,
  auditBody:"National authority (NÚKIB) / independent auditors", auditFreqEE:12, auditFreqIE:24, selfAssessFreq:12,
  regTool:"Platform (Portál NÚKIB)", incidentMethod:"Web platform (NÚKIB / national CERT)",
  summary:"In force Nov 2025 (12-month delay); strictest requirement count in the panel (296 EE measures); 6h early warning.",
  authorities:[
    { name:"NÚKIB", role:"National Cyber and Information Security Agency - supervision, dedicated portal" },
    { name:"National CERT", role:"Incident response for the lower-obligations regime" } ],
  sections:{
    fw:["Two regimes: higher obligations (≈EE, ISMS explicitly required) and lower obligations (≈IE).","OT/industrial control systems: dedicated technical measures (§27).","Entities have 12 months from registration to implement measures; 'strategically important services' carry extra supply-chain obligations."],
    reg:["Registration with NÚKIB within 60 days of the law entering into force (by 31 Dec 2025); asset inventory (primary + supporting) must be declared, exclusions justified.","Provider report within 30 days of registration decision; later changes notified within 90 days."],
    inc:["Early warning within 6 hours (24h for trust service providers) - stricter than the directive.","Incidents lasting over 1 month: supplementary reports every 15 days until the final report; reactive counter-measures ordered by the authority must be applied within 72h."],
    aud:["EE: annual security audits (first required from 1 Nov 2026); other entities every 2 years; independent auditors.","Cybersecurity audit at least every 2 years and on significant change (§16)."],
    scope:["Defence industry sector added; sub-sectors added: gas stations, electricity suppliers for data centres, in-flight refuelling, qualified e-ID systems, payment/e-money institutions, research infrastructure.","Regulator can designate critical exceptions; criticality criteria quantified in decree No. 408/2025."],
    reco:["Inventory primary and supporting assets required for the regulated service before registration."] },
  timeline:[
    { date:"2025-06-11", text:"Senate approves the bill; signed by the President 26 June 2025" },
    { date:"2025-08-04", text:"Act No. 264/2025 Coll. published in the Collection of Laws" },
    { date:"2025-10-14", text:"Two implementing decrees published (essential / important entities)" },
    { date:"2025-11-01", text:"Law and decrees enter into force" },
    { date:"2025-12-31", text:"Registration deadline (60 days) for regulated services" } ],
  next:["First audits required for essential entities from 1 Nov 2026."],
  sources:[
    { name:"NÚKIB", url:"https://nukib.gov.cz", type:"official" },
    { name:"Portál NÚKIB", url:"", type:"official" },
    { name:"Collection of Laws (Sbírka zákonů)", url:"", type:"official" } ] },

{ iso:"DE", name:"Germany", flag:"🇩🇪", region:"West", eu:true, maturity:4, lastUpdate:"2026-06-18",
  transposed:true, onTime:false, delayMonths:13, lawInForce:"2025-12-06", fw:"final",
  law:"NIS-2 Implementation Act (published 5 Dec 2025) + KRITIS-Dachgesetz (17 Mar 2026, CER)",
  fwName:"No single national standard - sector regulations + recognised standards (ISO 27001, BSI 200-3/200-4, B3S, KRITIS)",
  reqEE:93, reqIE:93, complianceEE:36, complianceIE:24,
  auditBody:"External accredited body", auditFreqEE:12, auditFreqIE:36, selfAssessFreq:24,
  regTool:"Platform + guide (Mein Unternehmenskonto → BSI portal)", incidentMethod:"Web platform (BSI)",
  summary:"In force Dec 2025; ~29,500 entities in scope, enforcement phase running - unregistered entities face fines up to €500k after 31 July 2026.",
  authorities:[
    { name:"BSI", role:"Federal Office for Information Security - supervision, registration, incident notification" },
    { name:"BBK", role:"Federal Office for Civil Protection and Disaster Assistance" } ],
  sections:{
    fw:["No dedicated NIS 2 standard: entities follow stricter sector regulation where it exists (e.g. DORA, EnWG for energy), otherwise choose recognised standards (ISO 27001, BSI 200-3/200-4, sectoral B3S, KRITIS).","Compliance required by 6 Dec 2028; proof of compliance renewed every 3 years.","Two entity categories: critical facilities (KRITIS + essential) and important facilities."],
    reg:["Registration due 6 Mar 2026 (or within 3 months of qualifying); ≈38.5% of ~29,500 entities registered at the deadline; BSI in active control phase since May 2026.","Unregistered entities asked to regularise by 31 Jul 2026, fines up to €500,000; registered data must be updated annually.","Digital-infrastructure and KRITIS entities provide extra data (public IP ranges, critical ICT services)."],
    inc:["Incidents reported to the BSI since the notification channel opened on 6 Jan 2026; standard NIS 2 deadlines; interim reports on BSI request."],
    aud:["KRITIS operators transmit audit/certification results and identified vulnerabilities to the BSI; remediation plans can be required.","Independent audits/inspections can be ordered ex-ante for essential entities, ex-post for others; proof requests possible at the earliest 3 years after the law."],
    scope:["Public sector = federal administration entities only; municipalities and non-federal administrations not automatically in scope; defence/interior exempt (reporting duties remain).","Health: major labs, R&D, medical facilities under NIS2+KRITIS; finance under DORA; space = ground infrastructure."],
    other:["DORA-regulated entities exempt from NIS 2; KRITIS framework recognised; seven-tier penalty scale up to €10M/2% (EE) and €7M/1.4% (IE), €500k tier for registration failures."],
    reco:["Executive members must complete cybersecurity risk training as soon as possible, then every 3 years; identify applicable standards or select a framework."] },
  timeline:[
    { date:"2025-11-13", text:"Bundestag adopts the NIS 2 transposition law" },
    { date:"2025-12-05", text:"Law published in the Federal Gazette; in force 6 Dec 2025" },
    { date:"2026-01-06", text:"BSI opens registration platform and incident notification form" },
    { date:"2026-03-06", text:"Registration deadline - ≈38.5% of in-scope entities registered" },
    { date:"2026-03-17", text:"KRITIS-Dachgesetz (physical resilience / CER) enters into force" },
    { date:"2026-05-15", text:"BSI enters active enforcement phase; regularisation demanded by 31 July 2026" } ],
  next:["By 6 Dec 2028: all registered entities fully compliant; proofs renewed every 3 years."],
  sources:[
    { name:"BSI", url:"https://www.bsi.bund.de", type:"official" },
    { name:"Federal Gazette (BGBl.)", url:"", type:"official" } ] },

{ iso:"GR", name:"Greece", flag:"🇬🇷", region:"South", eu:true, maturity:4, lastUpdate:"2026-07-02",
  transposed:true, onTime:false, delayMonths:1, lawInForce:"2024-11-27", fw:"final",
  law:"Law 5160/2024 + Ministerial Decision 1689/2025 (national framework)",
  fwName:"National framework - 22 mandatory cybersecurity controls (Decision 1689/2025)",
  reqEE:142, reqIE:134, complianceEE:18, complianceIE:18,
  auditBody:"National authority (NCSA)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:12,
  regTool:"Platform (NCSA digital platform)", incidentMethod:"Web platform + email (NCSA portal)",
  summary:"Law in force Nov 2024; 22-control national framework since May 2025; 2026-2030 national strategy adopted.",
  authorities:[
    { name:"NCSA", role:"National Cybersecurity Authority (cyber.gov.gr) - sole regulator and central contact point" },
    { name:"National CSIRT", role:"Incident management (EYP/NIS CERT for central government and municipalities)" },
    { name:"ADAE", role:"Contact point for electronic communications, with reinforced sectoral powers" } ],
  sections:{
    fw:["22 mandatory controls covering technical, organisational and operational aspects; no explicit reliance on an international standard.","Since 6 May 2025 the national framework is the mandatory reference for NCSA audits and inspections.","Local-specificity highlights: mandatory internal AND external penetration testing at least annually (or after major incident)."],
    reg:["Registration on the NCSA digital platform; final deadline extended to 30 Sep 2025.","Changes notified within 2 weeks (3 months for some digital providers); detailed data set incl. domain names; strict identification of 'critical' entities without size thresholds."],
    inc:["Online form on the NCSA portal + email; obligation applicable since entry into force.","Definition includes 'moral harm' and a preventive approach (notifiable as soon as an incident is 'likely' to have serious impact); NCSA can tighten criteria by decision."],
    aud:["On-site and off-site inspections incl. spot checks; special audits after incidents, complaints or serious indications; supervision of EE and IE security evaluation.","Appointment of an ICT Security Officer (Υ.Α.Σ.Π.Ε.) mandatory - role incompatible with DPO; full asset inventory classified by criticality required."],
    scope:["Special regimes: electronic communications (ADAE), energy incl. EV charging operators and hydrogen, space ground infrastructure, health manufacturing, MSP/MSSP essential regardless of size.","Local authorities in scope since 27 Nov 2025; central government reports incidents to the National CERT (EYP/NIS)."],
    other:["DORA is lex specialis for finance; NCSA coordination mechanism with sector regulators still maturing."] },
  timeline:[
    { date:"2024-11-27", text:"Law 5160/2024 enters into force" },
    { date:"2025-05-06", text:"Ministerial Decision 1689/2025: national framework of 22 controls published" },
    { date:"2025-09-30", text:"Extended registration deadline for data submission to the NCSA" },
    { date:"2025-11-27", text:"Law applies to local authorities (regions and municipalities)" },
    { date:"2025-12-16", text:"National Cybersecurity Strategy 2026-2030 adopted" } ],
  next:["Alignment with the 2026-2030 strategy: EL-SOC connection, future Cyber Hotline for incident support."],
  sources:[
    { name:"NCSA - cyber.gov.gr", url:"https://cyber.gov.gr", type:"official" },
    { name:"Government Gazette (FEK)", url:"", type:"official" } ] },

{ iso:"HU", name:"Hungary", flag:"🇭🇺", region:"East", eu:true, maturity:4, lastUpdate:"2026-07-06",
  transposed:true, onTime:false, delayMonths:9, lawInForce:"2025-01-03", fw:"final",
  law:"Cybersecurity Act LXIX of 2024 + implementing decrees (Jan 2025)",
  fwName:"Three security classes - Basic / Significant / High: 120 / 200 / 280 measures",
  reqEE:150, reqIE:110, complianceEE:24, complianceIE:24,
  auditBody:"External accredited body", auditFreqEE:24, auditFreqIE:null, selfAssessFreq:24,
  regTool:"Form (SZTFH 420)", incidentMethod:"Report to Special Service for National Security",
  summary:"In force Jan 2025; classification of IS in 3 security classes; audit deadline extended to 30 June 2026; supervision fee regime.",
  authorities:[
    { name:"SZTFH / SARA", role:"National transposition and supervision authority" },
    { name:"NKI", role:"Defence cybersecurity authority" },
    { name:"KNBSZ", role:"CERT and certification authority (intelligence services)" },
    { name:"Special Service for National Security", role:"National cybersecurity incident management centre" } ],
  sections:{
    fw:["EE must classify information systems into Basic / Significant / High classes; IE must at least meet the Basic class within 1 year.","Data hosted on public cloud or abroad must be classified by confidentiality, integrity, availability.","Compliance demonstrated using ICT services/products/processes certified under a European or national scheme; 2 years granted to EE for security measures."],
    reg:["Registration via form SZTFH 420 within 30 days; authority reviews and issues a decision; updates within 15 days.","Annual supervision fee payable to the SZTFH (decree 2/2025)."],
    inc:["Incidents reported to the Special Service for National Security; incident management plan mandatory; beneficiaries informed within 72h.","Sectoral variations: reporting requirements can differ by sector and competent incident centre."],
    aud:["Contract with an SZTFH-approved audit body was due by 31 Aug 2025; first audit by 30 Jun 2026 (extension approved 2 Oct 2025).","Classification and security policy reviewed at least every 2 years; failed audits trigger a remediation plan within 90 days."],
    scope:["Cement/lime/gypsum production added to Manufacturing; electronic communications services added as highly critical.","Banking and financial market infrastructure excluded (DORA); public administration sector not listed; public transport sub-sector added."],
    other:["Law implements NIS 2 and CER, referencing ENISA and DORA regulations."],
    reco:["Run the IS risk analysis to determine the security class; contract an approved auditor; start data classification (Basic/Significant/High)."] },
  timeline:[
    { date:"2025-01-03", text:"Cybersecurity Act LXIX in force (government + ministerial decrees Jan 2025)" },
    { date:"2025-01-31", text:"SZTFH decrees on audit procedure and supervision fees published" },
    { date:"2025-07-31", text:"Law XXIII in force; supervision fees due" },
    { date:"2025-10-02", text:"Audit deadlines extended: auditor contract 31 Aug 2025, first audit 30 Jun 2026" } ],
  next:["Several clarifying regulations still expected."],
  sources:[
    { name:"SZTFH", url:"https://sztfh.hu", type:"official" },
    { name:"Magyar Közlöny (Official Gazette)", url:"", type:"official" } ] },

{ iso:"IT", name:"Italy", flag:"🇮🇹", region:"South", eu:true, maturity:4, lastUpdate:"2026-06-24",
  transposed:true, onTime:true, delayMonths:0, lawInForce:"2024-10-16", fw:"final",
  law:"Legislative Decree 138/2024 + ACN Decision No. 164179 (10 Apr 2025)",
  fwName:"NIST CSF 2.0-based framework - EE: 43 measures / 116 req.; IE: 37 measures / 87 req.",
  reqEE:116, reqIE:87, complianceEE:18, complianceIE:18,
  auditBody:"National authority (ACN)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Platform (ACN services portal)", incidentMethod:"Web platform (CSIRT Italia form)",
  summary:"Transposed on time; NIST CSF 2.0 framework; incident notification binding since 15 Jan 2026; measures due by 1 Oct 2026.",
  authorities:[
    { name:"ACN", role:"Agenzia per la Cybersicurezza Nazionale - national authority" },
    { name:"Sector ministries", role:"Sectoral authorities per NIS 2 sector" },
    { name:"CSIRT Italia", role:"National CSIRT - incident notifications" } ],
  sections:{
    fw:["Framework built on the 6 NIST CSF 2.0 functions (GV, ID, PR, DE, RS, RC); measures in annexes 1-2 of Decision 164179.","EE-only additions: periodic vulnerability/penetration testing, secure baseline configurations, secure hardware decommissioning, inbound traffic filtering incl. email.","Implementation of security measures due by 1 Oct 2026 (18 months after ACN validation)."],
    reg:["Registration on the ACN portal 1 Dec 2024 - 28 Feb 2025 (17 Jan for digital providers); ACN validation notified 15 Apr 2025 triggering all deadlines; annual updates (activities, NIS contact + substitute).","Data includes Codice Fiscale, security officers, public IPs/domains, EU member states served; changes within 14 days."],
    inc:["Notification to CSIRT Italia via form, binding since 15 Jan 2026 (9 months after registration).","Trigger criteria IS-1 to IS-4 (confidentiality, integrity, service levels, unauthorised access) - IS-4 applies to EE only."],
    aud:["ACN may review documentation, run on-site/remote inspections incl. random checks; regular or ad-hoc audits after major incidents.","Self-assessments mandatory for EE and IE; first one from 16 Oct 2026 (no frequency set yet)."],
    scope:["Public administration broadly covered: constitutional bodies, ministries, tax agencies, independent authorities; via annex, all local/regional authorities and publicly controlled bodies."] },
  timeline:[
    { date:"2024-10-16", text:"Legislative Decree 138/2024 in force - on time" },
    { date:"2025-04-10", text:"ACN decisions 164179 (framework), 136117 (portal), 136118 (info-sharing) published" },
    { date:"2025-04-14", text:"NIS Guidelines (basic technical specifications) published" },
    { date:"2025-05-31", text:"Annual information update + substitute contact designation completed" },
    { date:"2026-01-15", text:"Incident notification to CSIRT Italia becomes enforceable" } ],
  next:["By 1 Oct 2026: security measures of the 2025 Italian framework fully implemented."],
  sources:[
    { name:"ACN", url:"https://www.acn.gov.it", type:"official" },
    { name:"CSIRT Italia", url:"https://www.csirt.gov.it", type:"official" },
    { name:"Gazzetta Ufficiale", url:"", type:"official" } ] },

{ iso:"LV", name:"Latvia", flag:"🇱🇻", region:"North", eu:true, maturity:4, lastUpdate:"2026-07-03",
  transposed:true, onTime:true, delayMonths:0, lawInForce:"2024-09-01", fw:"final",
  law:"National Cybersecurity Law (in force 1 Sep 2024) + Regulation No. 397 + Minimum Cybersecurity Requirements (2 Jul 2025)",
  fwName:"Minimum Cybersecurity Requirements - 94 measures, Class A/B/C system",
  reqEE:87, reqIE:80, complianceEE:12, complianceIE:12,
  auditBody:"External accredited body", auditFreqEE:12, auditFreqIE:36, selfAssessFreq:12,
  regTool:"Form (annex 10, official e-address)", incidentMethod:"Email forms 1-5 (24h) to national security service",
  summary:"Transposed on time; 94-measure framework scaled by A/B/C classes; cybersecurity manager with citizenship rules for critical ICT.",
  authorities:[
    { name:"NCSC (Ministry of Defence)", role:"National Cybersecurity Centre - policy and supervision" },
    { name:"SAB", role:"Constitution Protection Bureau - critical ICT oversight" },
    { name:"CERT.LV", role:"Incident response, prevention, SOC supervision" },
    { name:"MilCERT", role:"Defence-sector incident response" } ],
  sections:{
    fw:["Requirements scaled by confidentiality/integrity/availability class (A/B/C): prescriptive log retention (18/12/6 months, NTP Stratum 2+ timestamps), MFA rules, encryption baselines.","Cybersecurity manager to be appointed (vetted; Latvian citizen for critical ICT infrastructure); first self-assessment report was due 1 Oct 2025.","Cybersecurity policy reviewed and communicated to the authority every 3 years; single national Internet traffic bridge for State-linked EE/IE."],
    reg:["Self-assessment test by 1 Apr 2025 then registration form (annex 10) via official e-address; extra notification for critical ICT owners; changes within 2 weeks."],
    inc:["Incidents reported within 24h to the specialised national security service via staged forms (early warning → final report); reporting live since 1 Jul 2025.","Vulnerabilities: report to the authority within 5 days; remediation 90 days (180 if technically impossible)."],
    aud:["NCSC can run or order compliance audits on suspicion of violations; independent certified auditors (ISO 27001, CISSP, CISA, CISM; ≥2 years experience), costs borne by the entity.","Annual self-assessment for the most critical classes, every 3 years otherwise."],
    scope:["EE: institutions directly/indirectly linked to the State, sole providers of a service in Latvia, EU reference labs; IE: mid-size security/education/trust service providers.","Outsourcing restricted by country/ownership with prior authority opinion; official register of authorised auditors."] },
  timeline:[
    { date:"2024-09-01", text:"National Cybersecurity Law in force - on time" },
    { date:"2025-02-02", text:"Regulation No. 397 on minimum cybersecurity requirements in force" },
    { date:"2025-07-02", text:"'Minimum Cybersecurity Requirements' regulation approved (94 measures)" },
    { date:"2025-10-01", text:"Deadline: cybersecurity manager appointed + first self-assessment report" } ],
  next:["Additional sectoral regulatory texts expected."],
  sources:[
    { name:"Ministry of Defence - mod.gov.lv", url:"https://www.mod.gov.lv", type:"official" },
    { name:"CERT.LV", url:"https://cert.lv", type:"official" },
    { name:"Likumi.lv (legislation)", url:"https://likumi.lv", type:"official" } ] }
];
