const COUNTRIES_4 = [
{ iso:"NL", name:"Netherlands", flag:"🇳🇱", region:"West", eu:true, maturity:4, lastUpdate:"2026-06-22",
  transposed:false, onTime:false, delayMonths:null, lawInForce:null, fw:"final",
  law:"Cyberbeveiligingswet (Cbw) - adopted by the Tweede Kamer, before the Senate",
  fwName:"Cbw (NIS2) Control Framework - 17 control domains, 26 measures, 5-level maturity model",
  reqEE:130, reqIE:130, complianceEE:null, complianceIE:null,
  auditBody:"Multiple (sector ministries)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Platform (mijn.ncsc.nl - voluntary until in force)", incidentMethod:"Sectoral CSIRT + competent authority",
  summary:"Law targeted for 1 July 2026 (Senate pending); official control framework already published Sept 2025; ~8,000 entities in scope.",
  authorities:[
    { name:"NCSC-NL", role:"National Cyber Security Centre - implementation lead" },
    { name:"Ministry of Justice and Security", role:"Coordinating authority" },
    { name:"Sector ministries", role:"Supervisory authorities; sectoral CSIRTs for notifications" },
    { name:"NOREA / ADR", role:"IT auditors body & central government audit service - framework co-authors" } ],
  sections:{
    fw:["Cbw (NIS2) Control Framework (30 Sep 2025): 17 domains, 26 control measures, 5-category maturity model; not yet binding but expected reference for regulators.","Cbw sets the general frame; concrete rules come in sector ministerial regulations (6 ministries consulted drafts Nov-Dec 2025; education delayed).","Duty of care and 24h incident reporting apply immediately at entry into force; board members get a 2-year grace period to certify cybersecurity training."],
    reg:["Voluntary registration open on mijn.ncsc.nl; obligation starts with the law; NCSC self-assessment, FAQ and preparation recommendations online."],
    inc:["Multi-level system: notify the sectoral CSIRT AND the competent authority (supervising ministry); practical modalities (single platform vs sector portals) not yet confirmed."],
    aud:["EE: ex-ante controls; IE: ex-post (on signals or incidents); no violation found → costs not charged to the entity."],
    scope:["Higher education can be included by ministerial decree; municipalities, provinces and water boards included by default as EE - beyond the NIS 2 minimum."],
    other:["Ministry of Interior published a mapping NIS 2 measures ↔ ISO 27002; ENISA compliance guide referenced; sector-specific EU acts prevail when equivalent."] },
  timeline:[
    { date:"2025-09-30", text:"NCSC publishes the Cbw (NIS2) Control Framework" },
    { date:"2025-12-13", text:"Entry into force officially postponed to Q2 2026" },
    { date:"2026-04-15", text:"Tweede Kamer (lower house) adopts the law" },
    { date:"2026-06-02", text:"Eerste Kamer publishes its question report; Council of State opinion on the implementing decree" } ],
  next:["Entry into force targeted 1 Jul 2026 (possible slip to Q3); no transition period except governance training."],
  sources:[
    { name:"NCSC-NL", url:"https://www.ncsc.nl", type:"official" },
    { name:"mijn.ncsc.nl", url:"https://mijn.ncsc.nl", type:"official" },
    { name:"Internetconsultatie (drafts)", url:"https://www.internetconsultatie.nl", type:"official" } ] },

{ iso:"ES", name:"Spain", flag:"🇪🇸", region:"South", eu:true, maturity:2, lastUpdate:"2026-06-24",
  transposed:false, onTime:false, delayMonths:null, lawInForce:null, fw:"none",
  law:"Cybersecurity Coordination and Governance bill - in parliamentary procedure",
  fwName:"CCN-STIC 892 (PCE-NIS2) withdrawn Mar 2025; updated ENS-based framework in preparation",
  reqEE:null, reqIE:null, complianceEE:null, complianceIE:null,
  auditBody:"Multiple (CCN, State Secretariats, OCC)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"None yet", incidentMethod:"Plataforma Nacional de Notificación (planned, 24/7)",
  summary:"Bill approved in Council of Ministers Jan 2025, still in Parliament; CJEU referral June 2026; ENS mapping as interim guidance.",
  authorities:[
    { name:"CNC (planned)", role:"Centro Nacional de Ciberseguridad - future single competent authority & SPOC (to be created within 12 months of the law)" },
    { name:"CCN / OCC / Digital Transformation Ministry", role:"Control authorities per sector and entity category" },
    { name:"CCN-CERT / INCIBE-CERT / ESPDEF-CERT", role:"Reference CSIRTs (public / private / defence)" } ],
  sections:{
    fw:["CCN-CERT published then withdrew the CCN-STIC 892 compliance profile (PCE-NIS2, ENS-based); an updated framework is in preparation; ENS updates by decree.","Management bodies responsible for risk measures with periodic training; EE must prove compliance via certification, IE may self-assess; ENS profile counts as compliance evidence (draft)."],
    reg:["Draft: self-assessment and submission of information to the control authority within 3 months of EE/IE status; changes within 2 weeks; CNC registry of digital providers planned; no platform yet."],
    inc:["Notifications via the reference CSIRT on the Plataforma Nacional de Notificación y Seguimiento de Ciberincidentes (CCN-CERT run, 24/7); original NIS 2 deadlines."],
    aud:["EE: ex-ante (on-site inspections, periodic audits by ENS-accredited certification bodies); IE: ex-post on evidence."],
    other:["DORA financial entities explicitly excluded from risk/notification/supervision provisions; equivalent EU regulations prevail."] },
  timeline:[
    { date:"2025-01-14", text:"Bill approved by the Council of Ministers (urgent procedure)" },
    { date:"2025-03-28", text:"CCN-CERT withdraws CCN-STIC 892 v1; updated framework in progress" },
    { date:"2025-05-07", text:"EC reasoned opinion for failure to notify transposition" },
    { date:"2026-06-14", text:"European Commission refers Spain to the CJEU (with France)" } ],
  next:["Adoption by Parliament and publication in the BOE; new CCN-STIC 892; CNC created by royal decree within 12 months of entry into force."],
  sources:[
    { name:"CCN-CERT", url:"https://www.ccn-cert.cni.es", type:"official" },
    { name:"BOE (Official Gazette)", url:"https://www.boe.es", type:"official" } ] },

{ iso:"GB", name:"United Kingdom", flag:"🇬🇧", region:"West", eu:false, maturity:2, lastUpdate:"2026-06-22",
  transposed:false, onTime:false, delayMonths:null, lawInForce:null, fw:"none",
  law:"Cyber Security and Resilience Bill - before the House of Lords (not an EU transposition: updates the NIS Regulations 2018)",
  fwName:"Codes of Practice to be issued by the Secretary of State (admissible as compliance evidence)",
  reqEE:null, reqIE:null, complianceEE:null, complianceIE:null,
  auditBody:"Sectoral authorities (12 regulators)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"ICO registry (RDSP/RMSP)", incidentMethod:"24h initial / 72h full to regulators",
  summary:"CS&R Bill in the Lords since June 2026; Royal Assent expected late 2026, full implementation through 2028; two-tier penalty regime.",
  authorities:[
    { name:"DSIT", role:"Department for Science, Innovation and Technology - policy lead" },
    { name:"NCSC", role:"National Cyber Security Centre" },
    { name:"12 sector regulators + ICO", role:"Competent authorities; ICO registers digital & managed service providers" } ],
  sections:{
    fw:["Seven reform pillars: MSPs in scope, two-tier criticality oversight (ex-ante/ex-post), strengthened incident reporting, full cost recovery, decree-based updates, delegated scope extension, 'critical dependency' designations.","Secretary of State may issue Codes of Practice - breach is not an offence but admissible as evidence of (non-)compliance."],
    reg:["RDSP/RMSP must register with the ICO within 3 months of section 14 commencement; non-UK entities appoint a local representative; ICO shares registries with GCHQ/NCSC every 12 months; data-centre OES register within 3 months of designation; changes within 7 days."],
    inc:["Initial alert within 24h, full notification within 72h (OES, RDSP, RMSP); expanded impact criteria; third-party-caused incidents must reference the origin entity."],
    aud:["Designated authorities and appointed inspectors: premises entry, document seizure, interviews, security testing; Statement of Strategic Priorities aligns supervision with national security."],
    scope:["Data centres (1 MW / 10 MW thresholds), managed service providers, load controllers ≥300 MW, specific digital services; authorities can designate Critical Suppliers.","Applies to Crown data-centre services with security-service exceptions."],
    other:["Penalties: up to £10M/2% standard, £17M/4% serious, £100k/day continuing; mandatory ransomware-payment reporting under separate consideration."] },
  timeline:[
    { date:"2025-11-12", text:"CS&R Bill first reading, House of Commons" },
    { date:"2026-02-24", text:"Committee stage completed; amended version published 25 Feb" },
    { date:"2026-06-10", text:"Report stage and third reading - Commons approve the bill" },
    { date:"2026-06-17", text:"First reading in the House of Lords" } ],
  next:["Full Lords sequence then Royal Assent expected late 2026; phased commencement, full implementation expected through 2028."],
  sources:[
    { name:"UK Parliament - bills.parliament.uk", url:"https://bills.parliament.uk", type:"official" },
    { name:"DSIT / gov.uk", url:"https://www.gov.uk", type:"official" },
    { name:"NCSC UK", url:"https://www.ncsc.gov.uk", type:"official" } ] },

{ iso:"IE", name:"Ireland", flag:"🇮🇪", region:"West", eu:true, maturity:1, lastUpdate:"2026-06-24",
  transposed:false, onTime:false, delayMonths:null, lawInForce:null, fw:"none",
  law:"National Cyber Security Bill - General Scheme Aug 2024, before the Oireachtas since early 2026",
  fwName:"NCSC Risk Management Measures (16 RMMs, non-binding guidance); CyFun co-ownership, ISO 27001 & NIST CSF accepted",
  reqEE:null, reqIE:null, complianceEE:null, complianceIE:null,
  auditBody:"Sectoral NCAs (8 designated)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"'Am I in Scope?' tool; portal targeted July 2026", incidentMethod:"National CSIRT (NCSC)",
  summary:"Bill still in the Oireachtas; 16 RMMs published as compliance floor; 8 sectoral authorities pre-designated; registration portal targeted July 2026.",
  authorities:[
    { name:"NCSC (IE)", role:"Lead competent authority, national CSIRT, single point of contact" },
    { name:"8 sectoral NCAs", role:"CRU (energy/water), ComReg (digital), Central Bank, IAA, CRR, Transport, NTA, Health agency" } ],
  sections:{
    fw:["65-page RMM guidance (24 Jun 2025): 16 risk-management measures, non-binding today, compliance floor upon enactment.","Ireland co-owns the Belgian CyFun framework and is moving to ratify it as national certification scheme; ISO 27001 and NIST CSF 2.0 also accepted; SME-friendly national scheme in development."],
    reg:["Registration portal targeted for July 2026 with 3-month self-registration window (conditional on enactment); entities will register with their sectoral authority; 'Am I in Scope?' tool online.","Minimum data: contact details, NACE code, CRO number, sector, member states served."],
    inc:["Early warning to NCSC/CSIRT-IE within 24h, notification with initial assessment within 72h, final report within 1 month (per public drafts)."],
    aud:["EE: proactive supervision (regular audits, on-site/off-site inspections, scans); IE: reactive; temporary suspension of EE activities possible on non-compliance."],
    scope:["Named EE public bodies: Government Ministers, CSO, C&AG, Revenue, OPW, NSSO; all other public bodies default to IE."],
    other:["NCSC powers beyond NIS 2 (proactive scanning, consent-based sensors, DNS blocking) contested on fundamental-rights grounds; DORA lex specialis with Central Bank as NIS 2 NCA for finance; EC reasoned opinion May 2025."] },
  timeline:[
    { date:"2024-08-30", text:"General Scheme of the National Cyber Security Bill published" },
    { date:"2025-05-07", text:"EC reasoned opinion (after Nov 2024 formal notice)" },
    { date:"2025-06-24", text:"NCSC publishes 16 Risk Management Measures (RMM guidance)" },
    { date:"2026-01-15", text:"Bill under renewed examination in the Oireachtas" } ],
  next:["Detailed risk-management and incident-reporting guidelines, national strategy and cyber emergency plan being finalised."],
  sources:[
    { name:"NCSC Ireland", url:"https://www.ncsc.gov.ie", type:"official" },
    { name:"Oireachtas", url:"https://www.oireachtas.ie", type:"official" } ] },

{ iso:"NO", name:"Norway", flag:"🇳🇴", region:"North", eu:false, maturity:1, lastUpdate:"2026-06-24",
  transposed:false, onTime:false, delayMonths:null, lawInForce:null, fw:"none",
  law:"Digital Security Act (NIS 1) in force 1 Oct 2025; unified NIS 2 + CER bill being finalised",
  fwName:"Digital Security Regulation (NIS 1 requirements); NSM Fundamental Principles recommended meanwhile",
  reqEE:null, reqIE:null, complianceEE:null, complianceIE:null,
  auditBody:"Multiple (sectoral authorities; NSM default)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Notification to NSM + sector authority", incidentMethod:"Reports to sector authority, copy to NSM",
  summary:"EEA country: NIS 1 regime live since Oct 2025; NIS 2 incorporation planned during 2026, no new official date after slippage.",
  authorities:[
    { name:"Ministry of Justice and Public Security", role:"Legislative lead" },
    { name:"NSM", role:"National Security Authority - guidance (Veileder), default supervisor" },
    { name:"Sectoral authorities", role:"Supervision (e.g. NVE for energy)" } ],
  sections:{
    fw:["Current regime = NIS 1 via the Digital Security Act and its regulation: all-risk approach, proportionate measures, management personally responsible (art. 20), specific measures list (art. 21).","Government recommends applying NSM's Fundamental Principles of Cybersecurity while awaiting NIS 2."],
    reg:["Essential service providers self-identify 'without delay' to the NSM and the competent sector authority."],
    inc:["Reports to the sectoral supervisory authority with copy to NSM (national contact point)."],
    scope:["Energy already heavily regulated by NVE (IKT-forskrift) easing transition; NIS 2 scope will add rail, port, airport infrastructure via sector regulations."],
    other:["National Security Act (Sikkerhetsloven) prevails on national-security conflicts; certified ICT products can be required (CSA); NSM guides on nsm.no."] },
  timeline:[
    { date:"2023-12-15", text:"Storting adopts the Digital Security Act (NIS 1)" },
    { date:"2024-12-11", text:"Public consultation on the implementing regulation closes" },
    { date:"2025-10-01", text:"Digital Security Act and regulation in force (NIS 1)" } ],
  next:["NIS 2 incorporation into Norwegian law planned during 2026; unified NIS2+CER bill being finalised - adoption slipped, no new official date."],
  sources:[
    { name:"NSM", url:"https://nsm.no", type:"official" },
    { name:"Lovdata (legislation)", url:"https://lovdata.no", type:"official" } ] }
];

/* ---- Watch queue: items detected by the (simulated) automated collection pipeline ---- */
const WATCH_QUEUE = [
{ id:"w1", detected:"2026-07-06", iso:"FR", title:"Resilience bill scheduled for plenary examination in the July 2026 extraordinary session",
  summary:"Parliamentary agenda confirms the examination slot; enactment hoped during summer 2026.",
  source:{ name:"Assemblée nationale - legislative dossier", url:"https://www.assemblee-nationale.fr", type:"official" },
  status:"pending", action:"Add to France timeline" },
{ id:"w2", detected:"2026-07-02", iso:"DE", title:"BSI reminder campaign: unregistered NIS 2 entities must regularise by 31 July 2026",
  summary:"BSI communication reiterates fines up to €500,000 for entities that fail to register after the March deadline.",
  source:{ name:"BSI press release", url:"https://www.bsi.bund.de", type:"official" },
  status:"pending", action:"Add to Germany timeline + update registration section" },
{ id:"w3", detected:"2026-07-04", iso:"ES", title:"Updated CCN-STIC 892 compliance profile reportedly expected Q3 2026",
  summary:"Mentioned by a speaker at an industry event, relayed on LinkedIn. No official confirmation from CCN-CERT yet.",
  source:{ name:"LinkedIn - practitioner post", url:"", type:"unofficial" },
  status:"pending", action:"Verify against CCN-CERT before publication" },
{ id:"w4", detected:"2026-07-01", iso:"GB", title:"CS&R Bill: House of Lords Second Reading scheduled",
  summary:"Parliamentary calendar shows the second reading slot; committee stage to follow.",
  source:{ name:"UK Parliament - bill stages", url:"https://bills.parliament.uk", type:"official" },
  status:"pending", action:"Add to United Kingdom timeline" },
{ id:"w5", detected:"2026-07-03", iso:"RO", title:"DNSC risk-management order expected after the summer (sector working group)",
  summary:"Heard during a sector coordination meeting attended by Wavestone. Not yet public - internal flag until official publication.",
  source:{ name:"Sector working group - manual input (Wavestone consultant)", url:"", type:"manual" },
  status:"pending", action:"Keep internal; publish once the order is in Monitorul Oficial" },
{ id:"w6", detected:"2026-06-23", iso:"PT", title:"Regulamento 756/2026 published - QNRCS v2 becomes the national framework",
  summary:"Implementing regulation published in the Diário da República on 22 June, in force 23 June. Portugal moves to maturity level 4.",
  source:{ name:"Diário da República", url:"https://diariodarepublica.pt", type:"official" },
  status:"validated", validatedBy:"NIS 2 core team", validatedOn:"2026-06-25" },
{ id:"w7", detected:"2026-06-18", iso:"SE", title:"Blog claims MSB will postpone all NIS 2 supervision to 2027",
  summary:"Unsourced blog post; contradicted by the supervisory calendar published with SFS 2025:1506.",
  source:{ name:"Independent blog", url:"", type:"unofficial" },
  status:"rejected", validatedBy:"NIS 2 core team", validatedOn:"2026-06-20", rejectReason:"Contradicted by official source" }
];
