const COUNTRIES_3 = [
{ iso:"BG", name:"Bulgaria", flag:"🇧🇬", region:"East", eu:true, maturity:3, lastUpdate:"2026-07-06",
  transposed:true, onTime:false, delayMonths:16, lawInForce:"2026-02-17", fw:"none",
  law:"Cybersecurity Act amendment - adopted 5 Feb 2026, in force 17 Feb 2026",
  fwName:"Framework specifying technical & organisational requirements pending (≥3 ordinances to adopt)",
  reqEE:null, reqIE:null, complianceEE:null, complianceIE:null,
  auditBody:"Authority or accredited external auditor", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Authority-driven registry (platform TBA)", incidentMethod:"Form + platform (dedicated regulation pending)",
  summary:"Law finally in force Feb 2026 (16-month delay); framework and registration modalities still to be set by ordinance.",
  authorities:[
    { name:"Ministry of e-Government", role:"Supervision (with sector ministries: transport, energy, finance, health, water)" } ],
  sections:{
    fw:["At least 3 ordinances pending: minimum cybersecurity measures, telecom entities, national strategy - no technical framework formalised yet.","INFORB project with the Romanian DNSC provides practical guides for the food sector."],
    reg:["The authority determines entity status and enters it in a dedicated registry, then notifies the entity; opt-out from the info-sharing registry possible on notification; changes within 2 weeks.","No registration platform or deadline published yet."],
    inc:["Via form and platform to be specified in a dedicated regulation; NIS 2 deadlines (24h / 72h / 1 month) and report structure apply."],
    aud:["Planned or unannounced inspections, on-site or remote; possible after security breaches or suspected illegality; self-assessment with report possible.","Control authorities also include the Ministry of Defence, Ministry of Interior and State Agency for National Security (DANS)."],
    scope:["Sectors follow NIS 2 almost verbatim; food sector broader than annex II (any stage of production/processing/distribution).","Administrative entities (EA) form a third category besides EE and IE; scope automatic by sector and size, no threshold for telecoms, trust services, TLD registries, sole providers."],
    other:["Restrictions on non-EU ICT products/services under discussion; CER, eIDAS and Cybersecurity Act referenced."] },
  timeline:[
    { date:"2025-02-20", text:"Cybersecurity law adopted at first reading by the National Assembly" },
    { date:"2025-05-07", text:"EC reasoned opinion for failure to notify full transposition" },
    { date:"2026-02-05", text:"Bill adopted at second reading" },
    { date:"2026-02-17", text:"Law enters into force" } ],
  next:["First implementation deadlines; framework ordinance specifying technical and organisational requirements expected."],
  sources:[
    { name:"Ministry of e-Government", url:"", type:"official" },
    { name:"State Gazette", url:"https://dv.parliament.bg", type:"official" } ] },

{ iso:"PL", name:"Poland", flag:"🇵🇱", region:"East", eu:true, maturity:3, lastUpdate:"2026-07-06",
  transposed:true, onTime:false, delayMonths:16, lawInForce:"2026-04-03", fw:"none",
  law:"UC32 amendment to the National Cybersecurity System Act (signed 19 Feb 2026)",
  fwName:"No dedicated framework - ISMS required; PN-EN ISO/IEC 27001 & ISO 22301 recognised",
  reqEE:null, reqIE:null, complianceEE:24, complianceIE:24,
  auditBody:"National authority (Ministry of Digital Affairs + sectoral CERTs)", auditFreqEE:24, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Platform (S46 teleinformatics system)", incidentMethod:"Web platform (S46, sectoral CSIRT)",
  summary:"In force Apr 2026; ~42,000 entities in scope (incl. ~28,000 public); everything runs through the S46 platform; first EE audits by Apr 2028.",
  authorities:[
    { name:"Ministry of Digital Affairs", role:"Registry (Wykaz), large-scale incidents & crises; Government Plenipotentiary for coordination" },
    { name:"Sectoral competent authorities", role:"Supervision per sector" },
    { name:"CSIRT MON / NASK / GOV", role:"National CSIRTs + sectoral CSIRTs for incident reporting" } ],
  sections:{
    fw:["No national framework: entities implement an ISMS within 12 months; PN-EN ISO/IEC 27001 and ISO 22301 designated as comparable standards.","Full compliance required by 3 Apr 2027 (12 months); compliance audit within 24 months.","High-risk vendor (HRV) mechanism: designated ICT suppliers must be phased out by regulated entities."],
    reg:["Registration in the Wykaz registry via the S46 platform; entities already qualified on 3 Apr 2026 must self-assess and register by 3 Oct 2026; new entities within 6 months of meeting criteria.","Electronic application with qualified e-signature; changes within 14 days; authority can register entities ex officio."],
    inc:["Alerts to the sectoral CSIRT via the dedicated S46 platform; NIS 2 deadlines and report content; public/banking entities notify under adapted rules.","Entities must adapt their IS to the platform's technical requirements within 6 months."],
    aud:["EE: audits every 2 years (recurring every 36 months after first audit at 24 months); ex-ante + ex-post for EE, ex-post for IE; contest window 7 days.","Authority can require Polish translation of audit documents at the entity's cost; audits at entity's cost; first audits (and first possible fines) from 3 Apr 2028."],
    scope:["Mining sub-sector and managed cybersecurity providers added to energy; nuclear energy added; more precise sub-sector definitions (e.g. research institutions).","Public entities split: EE (public finance sector, research institutes) and IE (local budget units, local cultural institutions); ~28,000 public bodies in scope."],
    other:["DORA entities exempt from cyber rules and notifications; links with CER transposition and sectoral laws; fines up to €24M + daily penalties, payable within 14 days; 2 contact persons with vetted records; annual documented training for CEO and cyber officer."] },
  timeline:[
    { date:"2025-10-21", text:"Government approves the UC32 amendment transposing NIS 2" },
    { date:"2025-12-05", text:"First reading in the Sejm; referred exclusively to the digital affairs committee" },
    { date:"2026-02-19", text:"President Nawrocki signs the law (published 2 Mar 2026)" },
    { date:"2026-04-03", text:"Law enters into force" } ],
  next:["3 Oct 2026: self-assessment + S46 registration deadline; 3 Apr 2027: full compliance; 3 Apr 2028: first EE security audits."],
  sources:[
    { name:"Ministry of Digital Affairs", url:"https://www.gov.pl/web/cyfryzacja", type:"official" },
    { name:"Dziennik Ustaw (Journal of Laws)", url:"https://dziennikustaw.gov.pl", type:"official" } ] },

{ iso:"CY", name:"Cyprus", flag:"🇨🇾", region:"South", eu:true, maturity:4, lastUpdate:"2026-07-06",
  transposed:true, onTime:false, delayMonths:6, lawInForce:"2025-04-25", fw:"none",
  law:"Law N.60(I)/2025 amending the NIS law (in force 25 Apr 2025)",
  fwName:"Framework to be specified by the Digital Security Authority - publication expected",
  reqEE:null, reqIE:null, complianceEE:null, complianceIE:null,
  auditBody:"National authority (DSA)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"DSA list + online self-assessment tool", incidentMethod:"Online form or email to CSIRT-CY",
  summary:"Law in force Apr 2025; framework pending; notably strict timelines: 6h early warning, 15-day supplementary reports for long incidents.",
  authorities:[
    { name:"DSA", role:"Digital Security Authority (dsa.cy) - regulator with functional independence over public bodies" },
    { name:"CSIRT-CY", role:"National CSIRT - incident notifications" } ],
  sections:{
    fw:["The law carries the directive's security rules; the DSA may specify them and can require certified ICT products/services under EU cybersecurity certification schemes; national framework expected shortly."],
    reg:["DSA draws up and maintains the EE/IE list (reviewed every 2 years); entities provide directive-required data once notified; changes within 2 weeks (3 months for DNS/TLD/cloud/data centres/social platforms).","Online self-assessment tool available to check eligibility."],
    inc:["First notification within 6 hours of awareness (stricter than the 24h of the directive; 24h kept for trust service providers); initial assessment within 72h, final report within 1 month.","Incidents lasting over 1 month: progress reports every 15 days until the final report."],
    aud:["Warnings, binding remediation instructions, cessation orders, publication of violations; ex-ante and ex-post for EE, ex-post for IE."],
    scope:["Banking stays in scope for national strategy, large-scale incident cooperation and CSIRT assistance, but is not DSA-supervised (DORA).","Public bodies: certain enforcement measures (certification suspension, management liability) do not apply."],
    other:["EU-CyCLONe participation enshrined; TLD/DNS databases must answer legitimate access requests within 72h; voluntary notifications accepted; active cyber-protection (network sensors) possible."] },
  timeline:[
    { date:"2024-11-28", text:"EC letter of formal notice for incomplete transposition" },
    { date:"2025-04-10", text:"House of Representatives votes law N.60(I)/2025" },
    { date:"2025-04-25", text:"Law enters into force" },
    { date:"2025-05-07", text:"EC reasoned opinion despite entry into force (incomplete notification)" } ],
  next:["National cybersecurity framework publication expected shortly."],
  sources:[
    { name:"DSA - dsa.cy", url:"https://dsa.cy", type:"official" },
    { name:"CSIRT-CY", url:"https://csirt.cy", type:"official" } ] },

{ iso:"DK", name:"Denmark", flag:"🇩🇰", region:"North", eu:true, maturity:3, lastUpdate:"2026-07-03",
  transposed:true, onTime:false, delayMonths:8, lawInForce:"2025-07-01", fw:"temporary",
  law:"NIS 2 Act (L 141 / LOV nr 434) + CER Act + sector laws (energy, telecom)",
  fwName:"Temporary framework 'Vejledning til NIS 2-loven' - 19 themes, 129 requirements (EE & IE)",
  reqEE:129, reqIE:129, complianceEE:null, complianceIE:null,
  auditBody:"Sectoral authorities", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Platform (Virk)", incidentMethod:"Web platform (Virk.dk → CFCS, auto-routed)",
  summary:"Main law in force July 2025; temporary 19-theme guidance (ISO 27001 / IEC 62443 / NIST CSF); sector-based supervision.",
  authorities:[
    { name:"Ministry of Resilience and Preparedness", role:"Lead for the main act" },
    { name:"SAMSIK", role:"Sector authority for central government, municipalities, parts of manufacturing/chemicals; overall coordination" },
    { name:"CFCS", role:"Centre for Cyber Security - national CSIRT (within FE)" },
    { name:"Named sector authorities", role:"Digital, finance, energy, health, transport, maritime, water, food" } ],
  sections:{
    fw:["Temporary framework with 19 themes / 129 requirements applying to EE and IE alike, based on ISO 27001, IEC 62443 and NIST CSF; sector guides expected.","Local specificities: explicit Single-Point-of-Failure identification in risk analysis; OT continuity and detection adapted to operational constraints."],
    reg:["EE/IE register within 2 weeks of falling in scope; digital service providers within 3 months; global registration deadline was 1 Oct 2025, via the national Virk platform."],
    inc:["Reports submitted digitally via Virk.dk, automatically routed to competent authorities, CSIRT and SPOC; CFCS offers anonymised pre-notification consultations; declarations since 1 Jul 2025."],
    aud:["Inspections in various forms (on-site or remote audits, document reviews) by sectoral authorities (energy agency, financial supervisory authority, health agency…)."],
    scope:["Central government units in scope by law; municipalities and regions as IE when acting commercially as public e-communications providers (>50 staff or >€10M).","Digital service providers in scope regardless of size."],
    other:["Financial sector transposition explicitly aligned with DORA under Finanstilsynet; evaluation report to Parliament within 3 years; nis2.dk hub with sector checklists and guides."] },
  timeline:[
    { date:"2025-03-07", text:"Energy sector law (No. 258, NIS 2 + CER) in force" },
    { date:"2025-04-29", text:"Parliament approves L 141 (NIS 2) and L 140 (CER)" },
    { date:"2025-06-15", text:"CFCS publishes implementation guides incl. the temporary framework" },
    { date:"2025-07-01", text:"Main law, CER law and telecom law in force" },
    { date:"2025-10-01", text:"Global registration deadline on Virk" } ],
  next:["Sector-specific guides refining the measures expected; evaluation report within 3 years."],
  sources:[
    { name:"CFCS", url:"https://www.cfcs.dk", type:"official" },
    { name:"nis2.dk portal", url:"https://nis2.dk", type:"official" },
    { name:"Virk", url:"https://virk.dk", type:"official" } ] },

{ iso:"FI", name:"Finland", flag:"🇫🇮", region:"North", eu:true, maturity:3, lastUpdate:"2026-07-06",
  transposed:true, onTime:false, delayMonths:5, lawInForce:"2025-04-08", fw:"temporary",
  law:"Cybersecurity Act (approved 11 Mar 2025, in force 8 Apr 2025)",
  fwName:"Traficom recommendation - 12 requirements mapped to ISO 27001, IEC 62443, NIST CSF/SP 800-53",
  reqEE:77, reqIE:77, complianceEE:3, complianceIE:3,
  auditBody:"National authority (Traficom) + sector authorities", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Platform (per sector authority, with fees)", incidentMethod:"Web platform (NCSC-FI CSIRT)",
  summary:"Law in force Apr 2025; 12 requirements detailed by Traficom recommendation; registration fees; CER law since July 2025.",
  authorities:[
    { name:"LVM", role:"Ministry of Transport and Communications - transposition lead" },
    { name:"Traficom / NCSC-FI", role:"Single national contact point, national CSIRT" },
    { name:"Sector authorities", role:"Energy Authority, Tukes, Valvira, Fimea, Food Authority, ELY centre, FIN-FSA" } ],
  sections:{
    fw:["The law defines 12 requirements mirroring the directive; Traficom recommendations detail the associated measures, mapped to the EU directive, the act, ISO and NIST standards.","Risk-management model due within 3 months of entry into force (risk identification, procedures/responsibilities/objectives, protective measures)."],
    reg:["Registration within 1 month (May 2025) with the sector supervisory authority (multi-sector entities register with each); registration and annual maintenance fees apply.","Digital entities (DNS, marketplaces, cloud…) provide extended data."],
    inc:["Significant incidents to the NCSC-FI CSIRT via the dedicated platform since 8 Apr 2025; 24h early warning, 72h report, final report 1 month later."],
    aud:["Supervisory authority can inspect premises/IS and require a security audit after a serious incident or substantial negligence."],
    scope:["Financial sector excluded (DORA); public sector handled via the public administration information management act.","Fines up to €10M or 2% of global turnover."],
    other:["FISC published a national NIS 2 application guide; EC reasoned opinion 7 May 2025 (incomplete notification); CER law in force 1 Jul 2025."] },
  timeline:[
    { date:"2025-03-11", text:"Parliament definitively approves the Cybersecurity Act" },
    { date:"2025-04-08", text:"Law in force; Traficom supervision recommendations published" },
    { date:"2025-07-01", text:"Critical infrastructure protection & resilience law (CER) in force" } ],
  next:["Sector technical regulations possible from supervisory authorities."],
  sources:[
    { name:"Traficom / NCSC-FI", url:"https://www.kyberturvallisuuskeskus.fi", type:"official" },
    { name:"Finlex (legislation)", url:"https://www.finlex.fi", type:"official" } ] },

{ iso:"SE", name:"Sweden", flag:"🇸🇪", region:"North", eu:true, maturity:3, lastUpdate:"2026-07-03",
  transposed:true, onTime:false, delayMonths:14, lawInForce:"2026-01-15", fw:"none",
  law:"Cybersäkerhetslag SFS 2025:1506 (approved 10 Dec 2025, in force 15 Jan 2026)",
  fwName:"All-risk measures across the 10 directive areas - additional regulations expected",
  reqEE:null, reqIE:null, complianceEE:null, complianceIE:null,
  auditBody:"Multiple (sectoral + 6 county boards)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Platform (MCF digital service)", incidentMethod:"IRON tool (provisional) → CERT-SE",
  summary:"Law in force Jan 2026 (14-month delay); registration since Feb 2026; provisional IRON incident tool; sector + regional supervision.",
  authorities:[
    { name:"MCF (Myndigheten för civilt försvar)", role:"Single point of contact, cyber crisis authority, national CSIRT (CERT-SE)" },
    { name:"Sectoral authorities", role:"PTS, energy agency, Transportstyrelsen, Finansinspektionen, health and food agencies" },
    { name:"6 county administrative boards", role:"Regional supervision (public administration, waste, research, some manufacturing)" } ],
  sections:{
    fw:["Technical, operational and organisational measures on an all-risk basis across the directive's 10 mandatory areas; no national framework published yet - additional regulations expected.","Lex specialis: Security Protection Act (SFS 2018:585) prevails where applicable; CER coordination - NIS 2 prevails unless CER is stricter."],
    reg:["Registration as of 2 Feb 2026 via the MCF digital service; supervisory action possible if no notification within 14 days; changes within 14 days; self-assessment of eligibility (registry incl. self-classification EE/IE)."],
    inc:["MCF is central recipient, reports transmitted to CERT-SE; provisional IRON tool until the new reporting tool ships; 24h/72h/1-month deadlines.","'Significant' quantified: >€500k or 5% turnover loss, trade-secret exfiltration, death or serious health damage, disruptive unauthorised access (EU implementing regulation)."],
    aud:["EE: controls any time (regular audits, targeted audits, technical scans, premises access); IE: only on suspicion of non-compliance; no violation found → costs not charged."],
    scope:["State authorities limited to those whose decisions affect cross-border mobility; regions, municipalities, municipal associations included; government, courts, Riksdag agencies excluded.","Fines payable within 30 days; uncollected after 5 years → cancelled; 40-year secrecy protection on incident-report information; Cybersäkerhetskollen maturity self-assessment tool."],
    other:["DORA entities exempt from NIS 2 security/notification duties; IMY informed immediately if personal-data breach found during control."] },
  timeline:[
    { date:"2025-06-12", text:"Government submits the new cybersecurity law proposal" },
    { date:"2025-12-10", text:"Riksdag approves 'en ny cybersäkerhetslag' (SFS 2025:1506)" },
    { date:"2026-01-15", text:"Cybersecurity law and regulation in force" },
    { date:"2026-02-02", text:"Registration opens (14-day duty)" } ],
  next:["Additional regulations (incl. MSB/MCF sector directives) expected."],
  sources:[
    { name:"MSB / MCF", url:"https://www.msb.se", type:"official" },
    { name:"CERT-SE", url:"https://www.cert.se", type:"official" },
    { name:"Riksdag (legislation)", url:"https://www.riksdagen.se", type:"official" } ] },

{ iso:"LU", name:"Luxembourg", flag:"🇱🇺", region:"West", eu:true, maturity:3, lastUpdate:"2026-06-19",
  transposed:true, onTime:false, delayMonths:19, lawInForce:"2026-05-10", fw:"none",
  law:"NIS 2 law promulgated 5 May 2026 (Mémorial A n°225) + CER law (n°226)",
  fwName:"No national framework yet - 10 minimum measures of art. 21 apply ('all-risks')",
  reqEE:null, reqIE:null, complianceEE:null, complianceIE:null,
  auditBody:"National authority (ILR; CSSF for finance)", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Platform (ILR portal)", incidentMethod:"Web platform (SERIMA)",
  summary:"Law in force May 2026 (~19-month delay); ILR self-registration due 10 July 2026; SERIMA platform for incidents & risk assessments.",
  authorities:[
    { name:"HCPN", role:"High Commission for National Protection - transposition, cross-border cooperation, major crises" },
    { name:"ILR", role:"Institut Luxembourgeois de Régulation - supervisory authority" },
    { name:"CSSF", role:"Financial sector supervision" },
    { name:"CIRCL", role:"National CSIRT for private EE/IE - notifications, technical assistance, CVD" },
    { name:"GOVCERT.lu", role:"CSIRT for State administrations, public establishments, CER critical entities" } ],
  sections:{
    fw:["Pending a national framework (temporary or definitive), entities apply the 10 minimum measures of article 21; management bodies approve and supervise risk measures, with mandatory regular training.","ILR sector regulations already published: transport (12 Nov 2025) and energy (4 Feb 2026), with OT security focus."],
    reg:["Self-registration on the ILR portal within 2 months of entry into force (by 10 Jul 2026); special-case digital providers had to register by 17 Jan 2025; annual updates and changes within 2 weeks; ILR reviews and confirms status; NIS 1 entities notified automatically."],
    inc:["Notification via the centralised SERIMA portal (launched 2 May 2025 for NIS/CCEE/GDPR/CER); NIS 2 deadlines; risk assessments standardised with the MONARC method."],
    aud:["Risk-based approach, no fixed frequency; full ILR controls expected from January 2027."],
    scope:["CER-designated critical entities automatically EE regardless of size; public entities explicitly EE with dedicated CSIRT; defence/intelligence/army exempt.","National EE/IE list updated at least every 2 years; authority can prescribe specific ICT products/services/processes."],
    other:["DORA entities exempt from equivalent provisions but still register with the ILR and notify non-DORA incidents; NIS 2 + GDPR notifications cumulative with anti-cumulation rule on fines."] },
  timeline:[
    { date:"2025-05-02", text:"Centralised incident portal launched on SERIMA" },
    { date:"2026-01-17", text:"Registration deadline for special-case digital providers" },
    { date:"2026-04-28", text:"Chamber of Deputies votes law 8364" },
    { date:"2026-05-05", text:"NIS 2 and CER laws promulgated (Mémorial A n°225-226)" },
    { date:"2026-05-10", text:"Law in force - NIS 1 law of 28 May 2019 repealed" } ],
  next:["10 Jul 2026: EE/IE self-registration deadline; ILR regulations/circulars on notifications and technical requirements; national framework to adopt; full controls from Jan 2027; SERIMA training sessions."],
  sources:[
    { name:"ILR", url:"https://www.ilr.lu", type:"official" },
    { name:"Legilux (legislation)", url:"https://legilux.public.lu", type:"official" } ] },

{ iso:"FR", name:"France", flag:"🇫🇷", region:"West", eu:true, maturity:2, lastUpdate:"2026-06-18",
  transposed:false, onTime:false, delayMonths:null, lawInForce:null, fw:"temporary",
  law:"'Résilience' bill (transposes NIS 2, DORA, CER) - awaiting plenary examination",
  fwName:"ANSSI ReCyF 2.5 (17 Mar 2026, provisional) - 20 themes, 152 EE / 76 IE measures",
  reqEE:152, reqIE:76, complianceEE:36, complianceIE:36,
  auditBody:"Multiple", auditFreqEE:null, auditFreqIE:null, selfAssessFreq:null,
  regTool:"Platform (ANSSI pre-registration)", incidentMethod:"N.C. (NIS 2 timelines expected)",
  summary:"Still not transposed - CJEU referral June 2026; ReCyF 2.5 provisional framework; plenary vote hoped for July 2026, ANSSI anticipates S2 2027.",
  authorities:[
    { name:"ANSSI", role:"National cybersecurity agency - framework, control and enforcement lead" } ],
  sections:{
    fw:["ReCyF 2.5 (17 Mar 2026): 20 themes across governance, protection, defence, resilience; 152 measures for EE, 76 for IE; framework comparison tool published.","An ephemeral 'NIS2+' variant was floated (excluding some sectors such as cosmetics distribution), shared with selected stakeholders only.","Presumption of conformity: ISO 27001 certification usable for certain measures; compliance evaluations expected annually internally, EE risk-analysis review every 3 years."],
    reg:["Pre-registration open on the ANSSI website since 24 Nov 2025 (basic data; more expected in the final law); scope-check tool available (EE/IE classification)."],
    inc:["Incident notification expected to follow original NIS 2 timelines (24h / 72h / 1 month)."],
    scope:["Public administrations: local authorities >30,000 inhabitants, their management centres/fire services, State administrations, public industrial establishments, education/research establishments.","NIS 1 OSE automatically subject; software publishers under debate; OIV classification triggers automatic criticality uplift."],
    other:["Bill aligns NIS 2, CER (REC) and DORA in a single 'Résilience' law."],
    reco:["Confirm eligible entities with legal teams; pre-register with ANSSI; brief top management; consider early IS scoping and a gap analysis against the provisional ReCyF framework."] },
  timeline:[
    { date:"2024-10-15", text:"'Résilience' bill presented in Council of Ministers, tabled in the Senate" },
    { date:"2025-03-12", text:"Senate adopts the bill (61 committee amendments, 34 on NIS 2)" },
    { date:"2025-09-11", text:"National Assembly special committee adopts 245 amendments" },
    { date:"2025-11-24", text:"ANSSI opens its NIS 2 pre-registration platform" },
    { date:"2026-03-17", text:"ReCyF 2.5 provisional framework published" },
    { date:"2026-06-14", text:"European Commission refers France to the CJEU for non-transposition" } ],
  next:["Plenary examination in the July 2026 extraordinary session, enactment hoped summer 2026; ANSSI does not anticipate a permanent transposition before S2 2027."],
  sources:[
    { name:"ANSSI - cyber.gouv.fr", url:"https://cyber.gouv.fr", type:"official" },
    { name:"Sénat / Assemblée nationale (dossiers législatifs)", url:"https://www.assemblee-nationale.fr", type:"official" },
    { name:"Légifrance", url:"https://www.legifrance.gouv.fr", type:"official" } ] }
];
