/* ---- National cyber authorities and their verified feeds.
   Generated by agent-veille/discover_feeds.py - do not edit by hand.
   `kind` is measured, not assumed: rss = a feed that parses with dated
   entries, harvest = no feed but a news page whose links are readable,
   page = the site answers but offers neither, down = unreachable. ---- */
const AUTHORITY_FEEDS = [
 {
  "iso": "AT",
  "name": "nis.gv.at / CERT.at",
  "url": "https://www.cert.at",
  "site": "https://www.cert.at",
  "kind": "page",
  "entries": 0,
  "feedTitle": "",
  "lang": ""
 },
 {
  "iso": "BE",
  "name": "CCB - Centre for Cybersecurity Belgium",
  "url": "https://cert.be/en/rss",
  "site": "https://ccb.belgium.be",
  "kind": "rss",
  "entries": 10,
  "feedTitle": "CCB Advisories Feed",
  "lang": "en"
 },
 {
  "iso": "BG",
  "name": "Bulgarian cybersecurity authority",
  "url": "https://www.govcert.bg/feed/",
  "site": "https://www.cybersecurity.bg",
  "kind": "rss",
  "entries": 10,
  "feedTitle": "CERT Bulgaria",
  "lang": "bg-BG"
 },
 {
  "iso": "CY",
  "name": "DSA - Digital Security Authority",
  "url": "https://dsa.cy",
  "site": "https://dsa.cy",
  "kind": "page",
  "entries": 0,
  "feedTitle": "",
  "lang": ""
 },
 {
  "iso": "CZ",
  "name": "NUKIB",
  "url": "https://nukib.gov.cz/rss.xml",
  "site": "https://nukib.gov.cz",
  "kind": "rss",
  "entries": 15,
  "feedTitle": "Národní úřad pro kybernetickou a informační bezpečnost",
  "lang": "cs-cz"
 },
 {
  "iso": "DE",
  "name": "BSI",
  "url": "https://wid.cert-bund.de/content/public/securityAdvisory/rss",
  "site": "https://www.bsi.bund.de",
  "kind": "rss",
  "entries": 250,
  "feedTitle": "BSI Warn- und Informationsdienst (WID): Schwachstellen-Informationen (Security A",
  "lang": ""
 },
 {
  "iso": "DK",
  "name": "CFCS - Center for Cybersikkerhed",
  "url": "https://samsik.dk/feed/",
  "site": "https://www.cfcs.dk",
  "kind": "rss",
  "entries": 10,
  "feedTitle": "Styrelsen for Samfundssikkerhed",
  "lang": "da-DK"
 },
 {
  "iso": "EE",
  "name": "RIA - Information System Authority",
  "url": "https://www.ria.ee/rss-feeds/rss.xml",
  "site": "https://www.ria.ee",
  "kind": "rss",
  "entries": 100,
  "feedTitle": "RIA - Loome ja kaitseme koos maailma parimat digitaalset ühiskonda.",
  "lang": "et"
 },
 {
  "iso": "ES",
  "name": "INCIBE",
  "url": "https://www.incibe.es/rss.xml",
  "site": "https://www.incibe.es",
  "kind": "rss",
  "entries": 10,
  "feedTitle": "INCIBE",
  "lang": "es"
 },
 {
  "iso": "FI",
  "name": "Traficom / NCSC-FI",
  "url": "https://www.kyberturvallisuuskeskus.fi/feed/rss/fi",
  "site": "https://www.kyberturvallisuuskeskus.fi",
  "kind": "rss",
  "entries": 500,
  "feedTitle": "www.kyberturvallisuuskeskus.fi RSS",
  "lang": ""
 },
 {
  "iso": "FR",
  "name": "ANSSI",
  "url": "https://cyber.gouv.fr/actualites/rss/",
  "site": "https://cyber.gouv.fr",
  "kind": "rss",
  "entries": 20,
  "feedTitle": "Les actualités",
  "lang": "fr"
 },
 {
  "iso": "GB",
  "name": "NCSC UK",
  "url": "https://www.ncsc.gov.uk/api/1/services/v1/news-rss-feed.xml",
  "site": "https://www.ncsc.gov.uk",
  "kind": "rss",
  "entries": 20,
  "feedTitle": "News Feed",
  "lang": "en"
 },
 {
  "iso": "GR",
  "name": "National Cybersecurity Authority",
  "url": "https://mindigital.gr",
  "site": "https://mindigital.gr",
  "kind": "down",
  "entries": 0,
  "feedTitle": "",
  "lang": ""
 },
 {
  "iso": "HR",
  "name": "ZSIS / CERT.hr",
  "url": "https://www.cert.hr/feed/",
  "site": "https://www.cert.hr",
  "kind": "rss",
  "entries": 10,
  "feedTitle": "CERT.hr",
  "lang": "hr"
 },
 {
  "iso": "HU",
  "name": "NBSZ NKI",
  "url": "https://nki.gov.hu/it-biztonsag/hirek/feed/",
  "site": "https://nki.gov.hu",
  "kind": "rss",
  "entries": 20,
  "feedTitle": "IT Biztonsági hírek – Nemzeti Kiberbiztonsági Intézet",
  "lang": "en-US"
 },
 {
  "iso": "IE",
  "name": "NCSC Ireland",
  "url": "https://www.ncsc.gov.ie/news/alerts.rss",
  "site": "https://www.ncsc.gov.ie",
  "kind": "rss",
  "entries": 233,
  "feedTitle": "NCSC Alerts & Advisories",
  "lang": ""
 },
 {
  "iso": "IT",
  "name": "ACN",
  "url": "https://www.acn.gov.it",
  "site": "https://www.acn.gov.it",
  "kind": "page",
  "entries": 0,
  "feedTitle": "",
  "lang": ""
 },
 {
  "iso": "LT",
  "name": "NKSC",
  "url": "https://www.nksc.lt",
  "site": "https://www.nksc.lt",
  "kind": "down",
  "entries": 0,
  "feedTitle": "",
  "lang": ""
 },
 {
  "iso": "LU",
  "name": "ILR / GOVCERT.LU",
  "url": "https://www.govcert.lu/index.xml",
  "site": "https://www.govcert.lu",
  "kind": "rss",
  "entries": 191,
  "feedTitle": "GOVCERT.LU",
  "lang": "en"
 },
 {
  "iso": "LV",
  "name": "CERT.LV",
  "url": "https://cert.lv/lv/feed/atom/viss",
  "site": "https://cert.lv",
  "kind": "rss",
  "entries": 30,
  "feedTitle": "CERT.LV",
  "lang": ""
 },
 {
  "iso": "MT",
  "name": "MDIA / CIP",
  "url": "https://mdia.gov.mt/feed/",
  "site": "https://mdia.gov.mt",
  "kind": "rss",
  "entries": 10,
  "feedTitle": "MDIA",
  "lang": "en-GB"
 },
 {
  "iso": "NL",
  "name": "NCSC-NL",
  "url": "https://feeds.ncsc.nl/nieuws.rss",
  "site": "https://www.ncsc.nl",
  "kind": "rss",
  "entries": 328,
  "feedTitle": "Nationaal Cyber Security Centrum - Nieuwsberichten",
  "lang": "nl"
 },
 {
  "iso": "NO",
  "name": "NSM",
  "url": "https://nsm.no/rss/nyheter-fra-nsm/",
  "site": "https://nsm.no",
  "kind": "rss",
  "entries": 10,
  "feedTitle": "Nyheter fra NSM",
  "lang": ""
 },
 {
  "iso": "PL",
  "name": "CSIRT NASK / CERT Polska",
  "url": "https://cert.pl/atom.xml",
  "site": "https://cert.pl",
  "kind": "rss",
  "entries": 100,
  "feedTitle": "CERT Polska",
  "lang": ""
 },
 {
  "iso": "PT",
  "name": "CNCS",
  "url": "https://www.cncs.gov.pt",
  "site": "https://www.cncs.gov.pt",
  "kind": "down",
  "entries": 0,
  "feedTitle": "",
  "lang": ""
 },
 {
  "iso": "RO",
  "name": "DNSC",
  "url": "https://dnsc.ro/feed",
  "site": "https://dnsc.ro",
  "kind": "rss",
  "entries": 10,
  "feedTitle": "DNSC",
  "lang": "ro-ro"
 },
 {
  "iso": "SE",
  "name": "MSB / CERT-SE",
  "url": "https://www.cert.se/feed/atom.xml",
  "site": "https://www.cert.se",
  "kind": "rss",
  "entries": 20,
  "feedTitle": "CERT-SE",
  "lang": "sv-SE"
 },
 {
  "iso": "SI",
  "name": "SI-CERT / URSIV",
  "url": "https://www.cert.si/feed",
  "site": "https://www.cert.si",
  "kind": "rss",
  "entries": 10,
  "feedTitle": "SI CERT",
  "lang": "sl-SI"
 },
 {
  "iso": "SK",
  "name": "NBU SK",
  "url": "https://www.nbu.gov.sk",
  "site": "https://www.nbu.gov.sk",
  "kind": "page",
  "entries": 0,
  "feedTitle": "",
  "lang": ""
 }
];
