/* ---- Cyber-theme coverage, from the workbook's "Mapping cyber themes".
   Generated by tools/cyber_themes.py - do not edit by hand.
   Which themes each national framework covers, not how many rules it has.
   Partial on purpose: the sheet holds 9 of 29 countries. ---- */
const CYBER_THEMES = {
 "workbook": "CYBER WATCH5_Technical inventory.xlsx",
 "sheet": "Mapping cyber themes",
 "lastUpdate": "2025-07-30",
 "families": [
  {
   "family": "IS inventory",
   "themes": [
    "Carthography of IS"
   ]
  },
  {
   "family": "Governance",
   "themes": [
    "Cyber governance",
    "security policies",
    "Planning",
    "Information Security Management System",
    "Security roles",
    "Engagement et responsabilité en cybersécurité",
    "Les responsabilités des responsables de la cybersécurité et du responsable de l’entité",
    "Obligations and Liability of the Highest Management Bodies",
    "Procedures for Monitoring compliance",
    "Business environment"
   ]
  },
  {
   "family": "Third-party management",
   "themes": [
    "Third-party management",
    "Supply chain risk management"
   ]
  },
  {
   "family": "HR security",
   "themes": [
    "HR security",
    "Awareness-raising and training",
    "Personal safety",
    "Cyber hygiene and awareness"
   ]
  },
  {
   "family": "Risk management",
   "themes": [
    "Risk management",
    "Measures based on risk exposure and social and economic impact",
    "Security roles",
    "All-hazards approach and state of the art technology"
   ]
  },
  {
   "family": "Audits",
   "themes": [
    "Security audits"
   ]
  },
  {
   "family": "MCO/MCS",
   "themes": [
    "Mapping and MCO/MCS",
    "Maintenance",
    "divulgation des vulnérabilités",
    "Vulnerability management",
    "Management and disclosure of vulnerabiilties"
   ]
  },
  {
   "family": "Physical security",
   "themes": [
    "Physical security",
    "Physical and environmental protection"
   ]
  },
  {
   "family": "Hardening",
   "themes": [
    "Architecture security",
    "Hardening",
    "Basic network cybersecurity"
   ]
  },
  {
   "family": "Dedicated IS administration",
   "themes": [
    "Dedicated IS administration"
   ]
  },
  {
   "family": "Asset Management",
   "themes": [
    "Asset Management",
    "Secure Configuration of Hardware, Software, Services, and Networks"
   ]
  },
  {
   "family": "Incident management",
   "themes": [
    "Incident management"
   ]
  },
  {
   "family": "Detection",
   "themes": [
    "Supervision",
    "Continuous monitoring",
    "Anomalies and events",
    "Logging and liability",
    "Protection against malicious code",
    "System and information integrity"
   ]
  },
  {
   "family": "Resilience",
   "themes": [
    "Business continuity",
    "Backup Management"
   ]
  },
  {
   "family": "Cyber crisis management",
   "themes": [
    "Cyber crisis management",
    "Crisis exercises",
    "Communications",
    "Mitigation",
    "Improvement"
   ]
  },
  {
   "family": "Data security",
   "themes": [
    "Data security"
   ]
  },
  {
   "family": "Evaluation of the effectiveness of measures",
   "themes": [
    "Evaluation of the effectiveness of measures",
    "Purchase of systems and services"
   ]
  },
  {
   "family": "IAM",
   "themes": [
    "MFA",
    "Identity and access management (IAM)",
    "Access control"
   ]
  },
  {
   "family": "Cryptography",
   "themes": [
    "Cryptography and encryption"
   ]
  },
  {
   "family": "DevSecOps",
   "themes": [
    "Security in the development of IT",
    "Security in IT procurement",
    "Acquisition, development and maintenance",
    "Application security",
    "Hardware and Software Management"
   ]
  },
  {
   "family": "Industrial asset security",
   "themes": [
    "Industrial asset security"
   ]
  }
 ],
 "themeCount": 62,
 "countries": {
  "FR": {
   "country": "France",
   "themesCovered": 19,
   "themesTotal": 62,
   "families": [
    {
     "family": "IS inventory",
     "covered": 1,
     "of": 1,
     "themes": [
      "Carthography of IS"
     ],
     "familyCovered": true
    },
    {
     "family": "Governance",
     "covered": 1,
     "of": 10,
     "themes": [
      "Cyber governance"
     ],
     "familyCovered": true
    },
    {
     "family": "Third-party management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Third-party management"
     ],
     "familyCovered": true
    },
    {
     "family": "HR security",
     "covered": 1,
     "of": 4,
     "themes": [
      "HR security"
     ],
     "familyCovered": true
    },
    {
     "family": "Risk management",
     "covered": 1,
     "of": 4,
     "themes": [
      "Risk management"
     ],
     "familyCovered": true
    },
    {
     "family": "Audits",
     "covered": 1,
     "of": 1,
     "themes": [
      "Security audits"
     ],
     "familyCovered": true
    },
    {
     "family": "MCO/MCS",
     "covered": 1,
     "of": 5,
     "themes": [
      "Mapping and MCO/MCS"
     ],
     "familyCovered": true
    },
    {
     "family": "Physical security",
     "covered": 1,
     "of": 2,
     "themes": [
      "Physical security"
     ],
     "familyCovered": true
    },
    {
     "family": "Hardening",
     "covered": 2,
     "of": 3,
     "themes": [
      "Architecture security",
      "Hardening"
     ],
     "familyCovered": true
    },
    {
     "family": "Dedicated IS administration",
     "covered": 1,
     "of": 1,
     "themes": [
      "Dedicated IS administration"
     ],
     "familyCovered": true
    },
    {
     "family": "Asset Management",
     "covered": 0,
     "of": 2,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Incident management",
     "covered": 1,
     "of": 1,
     "themes": [
      "Incident management"
     ],
     "familyCovered": true
    },
    {
     "family": "Detection",
     "covered": 3,
     "of": 6,
     "themes": [
      "Supervision",
      "Continuous monitoring",
      "Protection against malicious code"
     ],
     "familyCovered": true
    },
    {
     "family": "Resilience",
     "covered": 1,
     "of": 2,
     "themes": [
      "Business continuity"
     ],
     "familyCovered": true
    },
    {
     "family": "Cyber crisis management",
     "covered": 2,
     "of": 5,
     "themes": [
      "Cyber crisis management",
      "Crisis exercises"
     ],
     "familyCovered": true
    },
    {
     "family": "Data security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Evaluation of the effectiveness of measures",
     "covered": 0,
     "of": 2,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "IAM",
     "covered": 1,
     "of": 3,
     "themes": [
      "Identity and access management (IAM)"
     ],
     "familyCovered": true
    },
    {
     "family": "Cryptography",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "DevSecOps",
     "covered": 0,
     "of": 5,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Industrial asset security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    }
   ]
  },
  "BE": {
   "country": "Belgium",
   "themesCovered": 21,
   "themesTotal": 62,
   "families": [
    {
     "family": "IS inventory",
     "covered": 1,
     "of": 1,
     "themes": [
      "Carthography of IS"
     ],
     "familyCovered": true
    },
    {
     "family": "Governance",
     "covered": 3,
     "of": 10,
     "themes": [
      "Cyber governance",
      "security policies",
      "Business environment"
     ],
     "familyCovered": true
    },
    {
     "family": "Third-party management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Supply chain risk management"
     ],
     "familyCovered": true
    },
    {
     "family": "HR security",
     "covered": 1,
     "of": 4,
     "themes": [
      "Awareness-raising and training"
     ],
     "familyCovered": true
    },
    {
     "family": "Risk management",
     "covered": 1,
     "of": 4,
     "themes": [
      "Risk management"
     ],
     "familyCovered": true
    },
    {
     "family": "Audits",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "MCO/MCS",
     "covered": 1,
     "of": 5,
     "themes": [
      "Maintenance"
     ],
     "familyCovered": true
    },
    {
     "family": "Physical security",
     "covered": 0,
     "of": 2,
     "themes": [],
     "familyCovered": true
    },
    {
     "family": "Hardening",
     "covered": 1,
     "of": 3,
     "themes": [
      "Hardening"
     ],
     "familyCovered": true
    },
    {
     "family": "Dedicated IS administration",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Asset Management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Asset Management"
     ],
     "familyCovered": true
    },
    {
     "family": "Incident management",
     "covered": 1,
     "of": 1,
     "themes": [
      "Incident management"
     ],
     "familyCovered": true
    },
    {
     "family": "Detection",
     "covered": 3,
     "of": 6,
     "themes": [
      "Supervision",
      "Continuous monitoring",
      "Anomalies and events"
     ],
     "familyCovered": true
    },
    {
     "family": "Resilience",
     "covered": 1,
     "of": 2,
     "themes": [
      "Business continuity"
     ],
     "familyCovered": true
    },
    {
     "family": "Cyber crisis management",
     "covered": 3,
     "of": 5,
     "themes": [
      "Communications",
      "Mitigation",
      "Improvement"
     ],
     "familyCovered": true
    },
    {
     "family": "Data security",
     "covered": 1,
     "of": 1,
     "themes": [
      "Data security"
     ],
     "familyCovered": true
    },
    {
     "family": "Evaluation of the effectiveness of measures",
     "covered": 1,
     "of": 2,
     "themes": [
      "Evaluation of the effectiveness of measures"
     ],
     "familyCovered": true
    },
    {
     "family": "IAM",
     "covered": 1,
     "of": 3,
     "themes": [
      "Identity and access management (IAM)"
     ],
     "familyCovered": true
    },
    {
     "family": "Cryptography",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "DevSecOps",
     "covered": 0,
     "of": 5,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Industrial asset security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    }
   ]
  },
  "HU": {
   "country": "Hungary",
   "themesCovered": 21,
   "themesTotal": 62,
   "families": [
    {
     "family": "IS inventory",
     "covered": 1,
     "of": 1,
     "themes": [
      "Carthography of IS"
     ],
     "familyCovered": true
    },
    {
     "family": "Governance",
     "covered": 2,
     "of": 10,
     "themes": [
      "security policies",
      "Planning"
     ],
     "familyCovered": true
    },
    {
     "family": "Third-party management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Supply chain risk management"
     ],
     "familyCovered": true
    },
    {
     "family": "HR security",
     "covered": 2,
     "of": 4,
     "themes": [
      "Awareness-raising and training",
      "Personal safety"
     ],
     "familyCovered": true
    },
    {
     "family": "Risk management",
     "covered": 1,
     "of": 4,
     "themes": [
      "Risk management"
     ],
     "familyCovered": true
    },
    {
     "family": "Audits",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "MCO/MCS",
     "covered": 1,
     "of": 5,
     "themes": [
      "Maintenance"
     ],
     "familyCovered": true
    },
    {
     "family": "Physical security",
     "covered": 2,
     "of": 2,
     "themes": [
      "Physical security",
      "Physical and environmental protection"
     ],
     "familyCovered": true
    },
    {
     "family": "Hardening",
     "covered": 0,
     "of": 3,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Dedicated IS administration",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Asset Management",
     "covered": 0,
     "of": 2,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Incident management",
     "covered": 1,
     "of": 1,
     "themes": [
      "Incident management"
     ],
     "familyCovered": true
    },
    {
     "family": "Detection",
     "covered": 3,
     "of": 6,
     "themes": [
      "Continuous monitoring",
      "Logging and liability",
      "System and information integrity"
     ],
     "familyCovered": true
    },
    {
     "family": "Resilience",
     "covered": 1,
     "of": 2,
     "themes": [
      "Business continuity"
     ],
     "familyCovered": true
    },
    {
     "family": "Cyber crisis management",
     "covered": 1,
     "of": 5,
     "themes": [
      "Communications"
     ],
     "familyCovered": true
    },
    {
     "family": "Data security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Evaluation of the effectiveness of measures",
     "covered": 2,
     "of": 2,
     "themes": [
      "Evaluation of the effectiveness of measures",
      "Purchase of systems and services"
     ],
     "familyCovered": true
    },
    {
     "family": "IAM",
     "covered": 2,
     "of": 3,
     "themes": [
      "Identity and access management (IAM)",
      "Access control"
     ],
     "familyCovered": true
    },
    {
     "family": "Cryptography",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "DevSecOps",
     "covered": 1,
     "of": 5,
     "themes": [
      "Security in IT procurement"
     ],
     "familyCovered": true
    },
    {
     "family": "Industrial asset security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    }
   ]
  },
  "DE": {
   "country": "Germany",
   "themesCovered": 22,
   "themesTotal": 62,
   "families": [
    {
     "family": "IS inventory",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Governance",
     "covered": 0,
     "of": 10,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Third-party management",
     "covered": 2,
     "of": 2,
     "themes": [
      "Third-party management",
      "Supply chain risk management"
     ],
     "familyCovered": true
    },
    {
     "family": "HR security",
     "covered": 3,
     "of": 4,
     "themes": [
      "HR security",
      "Awareness-raising and training",
      "Cyber hygiene and awareness"
     ],
     "familyCovered": true
    },
    {
     "family": "Risk management",
     "covered": 3,
     "of": 4,
     "themes": [
      "Risk management",
      "Measures based on risk exposure and social and economic impact",
      "All-hazards approach and state of the art technology"
     ],
     "familyCovered": true
    },
    {
     "family": "Audits",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "MCO/MCS",
     "covered": 3,
     "of": 5,
     "themes": [
      "Maintenance",
      "Vulnerability management",
      "Management and disclosure of vulnerabiilties"
     ],
     "familyCovered": true
    },
    {
     "family": "Physical security",
     "covered": 0,
     "of": 2,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Hardening",
     "covered": 0,
     "of": 3,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Dedicated IS administration",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Asset Management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Asset Management"
     ],
     "familyCovered": true
    },
    {
     "family": "Incident management",
     "covered": 1,
     "of": 1,
     "themes": [
      "Incident management"
     ],
     "familyCovered": true
    },
    {
     "family": "Detection",
     "covered": 0,
     "of": 6,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Resilience",
     "covered": 2,
     "of": 2,
     "themes": [
      "Business continuity",
      "Backup Management"
     ],
     "familyCovered": true
    },
    {
     "family": "Cyber crisis management",
     "covered": 2,
     "of": 5,
     "themes": [
      "Cyber crisis management",
      "Communications"
     ],
     "familyCovered": true
    },
    {
     "family": "Data security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Evaluation of the effectiveness of measures",
     "covered": 1,
     "of": 2,
     "themes": [
      "Evaluation of the effectiveness of measures"
     ],
     "familyCovered": true
    },
    {
     "family": "IAM",
     "covered": 2,
     "of": 3,
     "themes": [
      "MFA",
      "Access control"
     ],
     "familyCovered": true
    },
    {
     "family": "Cryptography",
     "covered": 1,
     "of": 1,
     "themes": [
      "Cryptography and encryption"
     ],
     "familyCovered": true
    },
    {
     "family": "DevSecOps",
     "covered": 1,
     "of": 5,
     "themes": [
      "Security in the development of IT"
     ],
     "familyCovered": true
    },
    {
     "family": "Industrial asset security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    }
   ]
  },
  "CZ": {
   "country": "Czechia",
   "themesCovered": 23,
   "themesTotal": 62,
   "families": [
    {
     "family": "IS inventory",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Governance",
     "covered": 3,
     "of": 10,
     "themes": [
      "security policies",
      "Information Security Management System",
      "Security roles"
     ],
     "familyCovered": true
    },
    {
     "family": "Third-party management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Third-party management"
     ],
     "familyCovered": true
    },
    {
     "family": "HR security",
     "covered": 3,
     "of": 4,
     "themes": [
      "HR security",
      "Awareness-raising and training",
      "Cyber hygiene and awareness"
     ],
     "familyCovered": true
    },
    {
     "family": "Risk management",
     "covered": 2,
     "of": 4,
     "themes": [
      "Risk management",
      "Security roles"
     ],
     "familyCovered": true
    },
    {
     "family": "Audits",
     "covered": 1,
     "of": 1,
     "themes": [
      "Security audits"
     ],
     "familyCovered": true
    },
    {
     "family": "MCO/MCS",
     "covered": 0,
     "of": 5,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Physical security",
     "covered": 1,
     "of": 2,
     "themes": [
      "Physical security"
     ],
     "familyCovered": true
    },
    {
     "family": "Hardening",
     "covered": 0,
     "of": 3,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Dedicated IS administration",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Asset Management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Asset Management"
     ],
     "familyCovered": true
    },
    {
     "family": "Incident management",
     "covered": 1,
     "of": 1,
     "themes": [
      "Incident management"
     ],
     "familyCovered": true
    },
    {
     "family": "Detection",
     "covered": 1,
     "of": 6,
     "themes": [
      "Supervision"
     ],
     "familyCovered": true
    },
    {
     "family": "Resilience",
     "covered": 2,
     "of": 2,
     "themes": [
      "Business continuity",
      "Backup Management"
     ],
     "familyCovered": true
    },
    {
     "family": "Cyber crisis management",
     "covered": 1,
     "of": 5,
     "themes": [
      "Communications"
     ],
     "familyCovered": true
    },
    {
     "family": "Data security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Evaluation of the effectiveness of measures",
     "covered": 0,
     "of": 2,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "IAM",
     "covered": 2,
     "of": 3,
     "themes": [
      "Identity and access management (IAM)",
      "Access control"
     ],
     "familyCovered": true
    },
    {
     "family": "Cryptography",
     "covered": 1,
     "of": 1,
     "themes": [
      "Cryptography and encryption"
     ],
     "familyCovered": true
    },
    {
     "family": "DevSecOps",
     "covered": 2,
     "of": 5,
     "themes": [
      "Acquisition, development and maintenance",
      "Application security"
     ],
     "familyCovered": false
    },
    {
     "family": "Industrial asset security",
     "covered": 1,
     "of": 1,
     "themes": [
      "Industrial asset security"
     ],
     "familyCovered": true
    }
   ]
  },
  "HR": {
   "country": "Croatia",
   "themesCovered": 12,
   "themesTotal": 62,
   "families": [
    {
     "family": "IS inventory",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Governance",
     "covered": 1,
     "of": 10,
     "themes": [
      "Engagement et responsabilité en cybersécurité"
     ],
     "familyCovered": true
    },
    {
     "family": "Third-party management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Supply chain risk management"
     ],
     "familyCovered": true
    },
    {
     "family": "HR security",
     "covered": 2,
     "of": 4,
     "themes": [
      "HR security",
      "Cyber hygiene and awareness"
     ],
     "familyCovered": true
    },
    {
     "family": "Risk management",
     "covered": 1,
     "of": 4,
     "themes": [
      "Risk management"
     ],
     "familyCovered": true
    },
    {
     "family": "Audits",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "MCO/MCS",
     "covered": 0,
     "of": 5,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Physical security",
     "covered": 1,
     "of": 2,
     "themes": [
      "Physical security"
     ],
     "familyCovered": true
    },
    {
     "family": "Hardening",
     "covered": 1,
     "of": 3,
     "themes": [
      "Basic network cybersecurity"
     ],
     "familyCovered": true
    },
    {
     "family": "Dedicated IS administration",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Asset Management",
     "covered": 0,
     "of": 2,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Incident management",
     "covered": 1,
     "of": 1,
     "themes": [
      "Incident management"
     ],
     "familyCovered": true
    },
    {
     "family": "Detection",
     "covered": 0,
     "of": 6,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Resilience",
     "covered": 1,
     "of": 2,
     "themes": [
      "Business continuity"
     ],
     "familyCovered": true
    },
    {
     "family": "Cyber crisis management",
     "covered": 0,
     "of": 5,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Data security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Evaluation of the effectiveness of measures",
     "covered": 0,
     "of": 2,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "IAM",
     "covered": 1,
     "of": 3,
     "themes": [
      "Access control"
     ],
     "familyCovered": true
    },
    {
     "family": "Cryptography",
     "covered": 1,
     "of": 1,
     "themes": [
      "Cryptography and encryption"
     ],
     "familyCovered": true
    },
    {
     "family": "DevSecOps",
     "covered": 1,
     "of": 5,
     "themes": [
      "Hardware and Software Management"
     ],
     "familyCovered": true
    },
    {
     "family": "Industrial asset security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    }
   ]
  },
  "LT": {
   "country": "Lithuania",
   "themesCovered": 15,
   "themesTotal": 62,
   "families": [
    {
     "family": "IS inventory",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Governance",
     "covered": 1,
     "of": 10,
     "themes": [
      "Les responsabilités des responsables de la cybersécurité et du responsable de l’entité"
     ],
     "familyCovered": true
    },
    {
     "family": "Third-party management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Supply chain risk management"
     ],
     "familyCovered": true
    },
    {
     "family": "HR security",
     "covered": 2,
     "of": 4,
     "themes": [
      "HR security",
      "Cyber hygiene and awareness"
     ],
     "familyCovered": true
    },
    {
     "family": "Risk management",
     "covered": 1,
     "of": 4,
     "themes": [
      "Risk management"
     ],
     "familyCovered": true
    },
    {
     "family": "Audits",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "MCO/MCS",
     "covered": 2,
     "of": 5,
     "themes": [
      "Maintenance",
      "divulgation des vulnérabilités"
     ],
     "familyCovered": true
    },
    {
     "family": "Physical security",
     "covered": 1,
     "of": 2,
     "themes": [
      "Physical security"
     ],
     "familyCovered": true
    },
    {
     "family": "Hardening",
     "covered": 0,
     "of": 3,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Dedicated IS administration",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Asset Management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Asset Management"
     ],
     "familyCovered": true
    },
    {
     "family": "Incident management",
     "covered": 1,
     "of": 1,
     "themes": [
      "Incident management"
     ],
     "familyCovered": true
    },
    {
     "family": "Detection",
     "covered": 0,
     "of": 6,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Resilience",
     "covered": 1,
     "of": 2,
     "themes": [
      "Business continuity"
     ],
     "familyCovered": true
    },
    {
     "family": "Cyber crisis management",
     "covered": 0,
     "of": 5,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Data security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Evaluation of the effectiveness of measures",
     "covered": 1,
     "of": 2,
     "themes": [
      "Evaluation of the effectiveness of measures"
     ],
     "familyCovered": true
    },
    {
     "family": "IAM",
     "covered": 2,
     "of": 3,
     "themes": [
      "MFA",
      "Access control"
     ],
     "familyCovered": true
    },
    {
     "family": "Cryptography",
     "covered": 1,
     "of": 1,
     "themes": [
      "Cryptography and encryption"
     ],
     "familyCovered": true
    },
    {
     "family": "DevSecOps",
     "covered": 0,
     "of": 5,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Industrial asset security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    }
   ]
  },
  "IT": {
   "country": "Italy",
   "themesCovered": 18,
   "themesTotal": 62,
   "families": [
    {
     "family": "IS inventory",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Governance",
     "covered": 1,
     "of": 10,
     "themes": [
      "Security roles"
     ],
     "familyCovered": true
    },
    {
     "family": "Third-party management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Supply chain risk management"
     ],
     "familyCovered": true
    },
    {
     "family": "HR security",
     "covered": 2,
     "of": 4,
     "themes": [
      "HR security",
      "Awareness-raising and training"
     ],
     "familyCovered": true
    },
    {
     "family": "Risk management",
     "covered": 2,
     "of": 4,
     "themes": [
      "Risk management",
      "Security roles"
     ],
     "familyCovered": true
    },
    {
     "family": "Audits",
     "covered": 1,
     "of": 1,
     "themes": [
      "Security audits"
     ],
     "familyCovered": true
    },
    {
     "family": "MCO/MCS",
     "covered": 2,
     "of": 5,
     "themes": [
      "Maintenance",
      "Vulnerability management"
     ],
     "familyCovered": true
    },
    {
     "family": "Physical security",
     "covered": 1,
     "of": 2,
     "themes": [
      "Physical security"
     ],
     "familyCovered": true
    },
    {
     "family": "Hardening",
     "covered": 1,
     "of": 3,
     "themes": [
      "Basic network cybersecurity"
     ],
     "familyCovered": true
    },
    {
     "family": "Dedicated IS administration",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Asset Management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Asset Management"
     ],
     "familyCovered": true
    },
    {
     "family": "Incident management",
     "covered": 1,
     "of": 1,
     "themes": [
      "Incident management"
     ],
     "familyCovered": true
    },
    {
     "family": "Detection",
     "covered": 0,
     "of": 6,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Resilience",
     "covered": 1,
     "of": 2,
     "themes": [
      "Business continuity"
     ],
     "familyCovered": true
    },
    {
     "family": "Cyber crisis management",
     "covered": 1,
     "of": 5,
     "themes": [
      "Communications"
     ],
     "familyCovered": true
    },
    {
     "family": "Data security",
     "covered": 1,
     "of": 1,
     "themes": [
      "Data security"
     ],
     "familyCovered": true
    },
    {
     "family": "Evaluation of the effectiveness of measures",
     "covered": 0,
     "of": 2,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "IAM",
     "covered": 2,
     "of": 3,
     "themes": [
      "Identity and access management (IAM)",
      "Access control"
     ],
     "familyCovered": true
    },
    {
     "family": "Cryptography",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "DevSecOps",
     "covered": 0,
     "of": 5,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Industrial asset security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    }
   ]
  },
  "GR": {
   "country": "Greece",
   "themesCovered": 23,
   "themesTotal": 62,
   "families": [
    {
     "family": "IS inventory",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Governance",
     "covered": 4,
     "of": 10,
     "themes": [
      "security policies",
      "Security roles",
      "Obligations and Liability of the Highest Management Bodies",
      "Procedures for Monitoring compliance"
     ],
     "familyCovered": true
    },
    {
     "family": "Third-party management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Third-party management"
     ],
     "familyCovered": true
    },
    {
     "family": "HR security",
     "covered": 2,
     "of": 4,
     "themes": [
      "HR security",
      "Awareness-raising and training"
     ],
     "familyCovered": true
    },
    {
     "family": "Risk management",
     "covered": 2,
     "of": 4,
     "themes": [
      "Risk management",
      "Security roles"
     ],
     "familyCovered": true
    },
    {
     "family": "Audits",
     "covered": 1,
     "of": 1,
     "themes": [
      "Security audits"
     ],
     "familyCovered": true
    },
    {
     "family": "MCO/MCS",
     "covered": 1,
     "of": 5,
     "themes": [
      "Vulnerability management"
     ],
     "familyCovered": true
    },
    {
     "family": "Physical security",
     "covered": 1,
     "of": 2,
     "themes": [
      "Physical and environmental protection"
     ],
     "familyCovered": true
    },
    {
     "family": "Hardening",
     "covered": 1,
     "of": 3,
     "themes": [
      "Basic network cybersecurity"
     ],
     "familyCovered": true
    },
    {
     "family": "Dedicated IS administration",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Asset Management",
     "covered": 1,
     "of": 2,
     "themes": [
      "Secure Configuration of Hardware, Software, Services, and Networks"
     ],
     "familyCovered": true
    },
    {
     "family": "Incident management",
     "covered": 1,
     "of": 1,
     "themes": [
      "Incident management"
     ],
     "familyCovered": true
    },
    {
     "family": "Detection",
     "covered": 3,
     "of": 6,
     "themes": [
      "Continuous monitoring",
      "Anomalies and events",
      "Protection against malicious code"
     ],
     "familyCovered": true
    },
    {
     "family": "Resilience",
     "covered": 1,
     "of": 2,
     "themes": [
      "Business continuity"
     ],
     "familyCovered": true
    },
    {
     "family": "Cyber crisis management",
     "covered": 0,
     "of": 5,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Data security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "Evaluation of the effectiveness of measures",
     "covered": 0,
     "of": 2,
     "themes": [],
     "familyCovered": false
    },
    {
     "family": "IAM",
     "covered": 1,
     "of": 3,
     "themes": [
      "Access control"
     ],
     "familyCovered": true
    },
    {
     "family": "Cryptography",
     "covered": 1,
     "of": 1,
     "themes": [
      "Cryptography and encryption"
     ],
     "familyCovered": true
    },
    {
     "family": "DevSecOps",
     "covered": 2,
     "of": 5,
     "themes": [
      "Security in the development of IT",
      "Hardware and Software Management"
     ],
     "familyCovered": true
    },
    {
     "family": "Industrial asset security",
     "covered": 0,
     "of": 1,
     "themes": [],
     "familyCovered": false
    }
   ]
  }
 }
};
