#!/usr/bin/env python3
"""Embed the slide template into the standalone HTML build.

    python3 tools/embed_deck_template.py     # -> src/reg/nis2/data_template.js

RegWatch is a single double-clickable file with no backend, so "Generate country
slides" has to build the .pptx in the browser. That needs the template on board.

The package is embedded byte-for-byte, DEFLATE and all. The browser inflates and
re-deflates the two slide parts with the native `DecompressionStream` /
`CompressionStream('deflate-raw')` APIs, so no zip library is vendored and the
payload stays at the template's real size (~130 KB, ~176 KB once base64'd).
"""

import base64
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "ressources" / "template-pays.pptx"
OUT_JS = ROOT / "src" / "reg" / "nis2" / "data_template.js"


def main():
    if not TEMPLATE.exists():
        raise SystemExit("template not found: %s - run tools/make_country_template.py" % TEMPLATE)

    raw = TEMPLATE.read_bytes()
    with zipfile.ZipFile(TEMPLATE) as z:
        slides = [(i.filename, i.file_size) for i in z.infolist()
                  if i.filename.startswith("ppt/slides/") and i.filename.endswith(".xml")]

    b64 = base64.b64encode(raw).decode("ascii")
    OUT_JS.write_text(
        "/* ---- Country slide template (pptx), base64.\n"
        "   Generated by tools/embed_deck_template.py - do not edit by hand. ---- */\n"
        'const DECK_TEMPLATE_B64 = "%s";\n' % b64,
        encoding="utf-8")

    print("template   : %s (%d KB)" % (TEMPLATE.name, len(raw) // 1024))
    for name, size in slides:
        print("  slide part: %-28s %d KB inflated" % (name, size // 1024))
    print("embedded   : %s (%d KB of base64)" % (OUT_JS.relative_to(ROOT), len(b64) // 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
