/* Embed real flag SVGs into the standalone build.
 *
 *   node tools/embed_flags.js <path to flag-icons repo>   # -> src/data_flags.js
 *
 * Emoji flags were the previous approach and they fail in two ways that matter
 * for a client demo: they render in the host OS's style (Apple's glossy pills on
 * a Mac), and on Windows they do not render as flags at all - the browser falls
 * back to the two regional-indicator letters, so "🇫🇷" shows up as "FR".
 *
 * Real SVGs render identically everywhere and stay sharp at any tile size.
 *
 * Source: github.com/lipis/flag-icons (MIT). The licence notice is carried into
 * the generated file, which is what MIT requires of a redistribution.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ISOS = ["AT","BE","BG","CY","CZ","DE","DK","EE","ES","FI","FR","GB","GR","HR",
              "HU","IE","IT","LT","LU","LV","MT","NL","NO","PL","PT","RO","SE","SI","SK","EU"];

const repo = process.argv[2];
if (!repo) { console.error("usage: node tools/embed_flags.js <flag-icons repo>"); process.exit(1); }
const dir = path.join(repo, "flags", "4x3");

const entries = [];
let bytes = 0;
for (const iso of ISOS) {
  const file = path.join(dir, iso.toLowerCase() + ".svg");
  if (!fs.existsSync(file)) { console.error("missing flag: " + iso); process.exit(1); }
  let svg = fs.readFileSync(file, "utf8")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/>\s+</g, "><")
    .replace(/\s{2,}/g, " ")
    .trim();
  /* Let CSS size the flag instead of the file's own width/height. */
  svg = svg.replace(/<svg([^>]*)>/, (m, attrs) =>
    "<svg" + attrs.replace(/\s(width|height)="[^"]*"/g, "") +
    ' preserveAspectRatio="xMidYMid slice" focusable="false" aria-hidden="true">');
  bytes += svg.length;
  entries.push("  " + iso + ": " + JSON.stringify(svg));
}

const out = path.join(ROOT, "src", "data_flags.js");
fs.writeFileSync(out,
  "/* ---- Country flags as inline SVG. Generated by tools/embed_flags.js.\n" +
  "   Do not edit by hand.\n\n" +
  "   Flags from flag-icons (github.com/lipis/flag-icons), MIT licence:\n" +
  "   Copyright (c) 2013 Panayiotis Lipiridis\n" +
  "   Permission is hereby granted, free of charge, to any person obtaining a copy\n" +
  "   of this software and associated documentation files (the \"Software\"), to deal\n" +
  "   in the Software without restriction. The above copyright notice and this\n" +
  "   permission notice shall be included in all copies. ---- */\n" +
  "const FLAGS = {\n" + entries.join(",\n") + "\n};\n" +
  "/* Inline flag markup for an ISO code, with a text fallback if we lack the SVG. */\n" +
  "function flagSvg(iso){\n" +
  "  return FLAGS[iso] || `<span class=\"flag-txt\">${iso}</span>`;\n" +
  "}\n", "utf8");

console.log(ISOS.length + " flags -> " + path.relative(ROOT, out) + " (" + Math.round(bytes / 1024) + " KB of SVG)");
