#!/usr/bin/env python3
"""Extract the workbook's KPI table into the tool.

    python3 tools/kpi_extract.py "ressources/CYBER WATCH5_Technical inventory.xlsx"

The "KPIs - WID" sheet is already tidy - one row per country per indicator, with
Region, Country, maturity, source tab, KPI name and value. That shape is exactly
what a configurable dashboard needs, so it is carried across as-is rather than
re-derived from the seven wide sheets.

Each KPI is typed on the way out, because the type decides the chart: a numeric
indicator gets a ranked bar of countries, a boolean or categorical one gets a
breakdown. Guessing that in the browser would mean re-parsing 957 values on
every render.

Output: data/kpis.json, src/reg/nis2/data_kpis.js
"""

import json
import re
import sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    raise SystemExit("pip install openpyxl")

ROOT = Path(__file__).resolve().parent.parent
SHEET = "KPIs - WID"
HEADER_ROW = 12

# Values that mean "not known". Kept out of the numbers, counted separately, so a
# chart never shows "NC" as if it were an answer.
BLANK = {"", "nc", "n.c.", "n. c.", "na", "n/a", "n.a.", "tbc", "tbd",
         "to complete", "-", "--", "?", "non communiqué"}

REGION_EN = {"Ouest": "West", "Est": "East", "Nord": "North", "Sud": "South"}
# The KPI sheet spells a few countries differently from the rest of the workbook.
COUNTRY_FIX = {"Czech Republic": "Czechia", "UK": "United Kingdom"}


def clean(value):
    if value is None:
        return ""
    if hasattr(value, "isoformat"):
        return value.isoformat()[:10]
    text = re.sub(r"\s+", " ", str(value)).strip().replace("—", "-").replace("–", "-")
    return "" if text.lower() in BLANK else text


def as_number(text):
    m = re.fullmatch(r"-?\d+(?:[.,]\d+)?", text.replace(" ", ""))
    if not m:
        return None
    n = float(m.group().replace(",", "."))
    return int(n) if n == int(n) else n


def type_of(values):
    """numeric | boolean | categorical | text - the chart follows from this."""
    known = [v for v in values if v]
    if not known:
        return "empty"
    if sum(1 for v in known if as_number(v) is not None) >= len(known) * 0.8:
        return "numeric"
    lowered = {v.strip().lower() for v in known}
    if lowered <= {"yes", "no", "oui", "non", "true", "false", "y", "n"}:
        return "boolean"
    return "categorical" if len(lowered) <= 8 else "text"


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    path = Path(sys.argv[1]).expanduser()
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb[SHEET]

    cols = {c.value: c.column_letter for c in ws[HEADER_ROW] if c.value}
    need = ["Region", "Country", "Niveau de maturité", "Onglet", "KPI", "Value"]
    missing = [n for n in need if n not in cols]
    if missing:
        raise SystemExit("colonnes absentes de la feuille KPI : %s" % ", ".join(missing))

    rows = []
    for r in range(HEADER_ROW + 1, ws.max_row + 1):
        get = lambda name: ws["%s%d" % (cols[name], r)].value
        country = clean(get("Country"))
        if not country:
            continue
        rows.append({
            "country": COUNTRY_FIX.get(country, country),
            "region": REGION_EN.get(clean(get("Region")), clean(get("Region"))),
            "maturity": as_number(clean(get("Niveau de maturité"))),
            "tab": clean(get("Onglet")),
            "kpi": clean(get("KPI")),
            "value": clean(get("Value")),
        })

    catalogue = {}
    for row in rows:
        key = row["kpi"]
        if not key:
            continue
        entry = catalogue.setdefault(key, {"kpi": key, "tab": row["tab"], "values": []})
        entry["values"].append(row["value"])

    for entry in catalogue.values():
        vals = entry.pop("values")
        entry["type"] = type_of(vals)
        entry["known"] = sum(1 for v in vals if v)
        entry["total"] = len(vals)

    kpis = sorted(catalogue.values(), key=lambda e: (e["tab"], e["kpi"]))
    payload = {"workbook": path.name, "rows": rows, "catalogue": kpis}

    (ROOT / "data" / "kpis.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    (ROOT / "src" / "reg" / "nis2" / "data_kpis.js").write_text(
        "/* ---- KPI table from the comparative workbook (sheet \"KPIs - WID\").\n"
        "   Generated by tools/kpi_extract.py - do not edit by hand.\n"
        "   Tidy shape: one row per country per indicator. `type` decides the\n"
        "   chart, so the browser never has to re-parse 957 values. ---- */\n"
        "const KPI_ROWS = %s;\nconst KPI_CATALOGUE = %s;\n"
        % (json.dumps(rows, ensure_ascii=False, separators=(",", ":")),
           json.dumps(kpis, ensure_ascii=False, indent=1)),
        encoding="utf-8")

    by_type = {}
    for e in kpis:
        by_type[e["type"]] = by_type.get(e["type"], 0) + 1
    print("%d lignes, %d KPI, %d pays" % (len(rows), len(kpis),
                                          len({r["country"] for r in rows})))
    print("  par type   : %s" % ", ".join("%s=%d" % kv for kv in sorted(by_type.items())))
    print("  par onglet : %s" % ", ".join(
        "%s=%d" % (t, sum(1 for e in kpis if e["tab"] == t))
        for t in sorted({e["tab"] for e in kpis})))
    return 0


if __name__ == "__main__":
    sys.exit(main())
